CREATE OR REPLACE FUNCTION OPENACCESS."DELETE_BY_SERVICE_CALL" 
(
  I_REMARKS IN VARCHAR2 , 
  I_SERVICE_NUMBER IN VARCHAR2 , 
  I_READING_MONTH IN VARCHAR2 , 
  I_READING_YEAR IN VARCHAR2 


) RETURN VARCHAR2 AS 

v_result1 varchar(300):='SUCCESS';
v_result2 varchar(300):='SUCCESS';
I_DEL_LEDGER  boolean:=TRUE; 
I_DEL_ES boolean :=TRUE; 
I_DEL_GS  boolean :=TRUE; 
I_DEL_MR  boolean :=TRUE; 

BEGIN
 DELETE_TXN.DELETE_BY_SERVICE(I_REMARKS,I_SERVICE_NUMBER,I_READING_MONTH,I_READING_YEAR,'Y','Y','Y','Y',v_result1,v_result2);

return v_result1;

END DELETE_BY_SERVICE_CALL;

