CREATE OR REPLACE FUNCTION OPENACCESS."DELETE_ALL_GRID_CONNECTIVITY" RETURN VARCHAR2 AS
BEGIN


  DELETE FROM  T_GC_TRANSFORMERS;
  DELETE FROM  T_GC_APPLICATION_STATUS;
  DELETE FROM  T_GC_LOAN ;
  DELETE FROM  T_GC_ID_TABLEA;
  DELETE FROM  T_GC_ID_TABLEB;
  DELETE FROM  T_GC_QUANTUM_ALLOCATION;
  DELETE FROM  T_GC_CHECKLIST;
  DELETE FROM  T_GC_GEN_UNIT;
  DELETE FROM  T_GRID_CONN_APPLN ;
  DELETE FROM  T_GRID_CONNECTIVITY ;



 COMMIT;

 return 'SUCCESS';
 END DELETE_ALL_GRID_CONNECTIVITY ;

