CREATE OR REPLACE FUNCTION OPENACCESS."TO_CALL_SURPLUS_LOSS_CALC" 
--AUTHOR: AE/LT5
(GENERATOR_CODE IN VARCHAR2,
SUPPLIER_CODE IN VARCHAR2,
DRAWAL_UNITS IN VARCHAR2,

TRANS_LOSS OUT NUMBER,DIST_LOSS OUT NUMBER,
TOTAL_LOSS OUT NUMBER,INJECTED_UNITS OUT NUMBER)
RETURN VARCHAR2 AS 
BEGIN


  RETURN NULL;
END;

