CREATE OR REPLACE FUNCTION OPENACCESS."UPDATE_SUBSTATION" RETURN VARCHAR2 AS 
v_ss_cur sys_refcursor ;
v_pp M_POWERPLANT%ROWTYPE;
BEGIN
	OPEN v_ss_cur for select * from m_powerplant;
    LOOP 
    FETCH v_ss_cur INTO v_pp;
    UPDATE M_COMPANY_SERVICE SET M_SUBSTATION_ID=v_pp.M_SUBSTATION_ID WHERE ID=v_pp.M_SERVICE_ID and M_SUBSTATION_ID is null;
	EXIT WHEN v_ss_cur%NOTFOUND;

	END LOOP;
  RETURN 'success';
END UPDATE_SUBSTATION;

