export class BankingBalance{
      id ?:string;
	  bankingCompanyId ?:string;
	  bankingServiceId ?:string;
	  c1 ?:string;
	  c2 ?:string;
	  c3 ?:string;
	  c4 ?:string;
	  c5 ?:string;
	  currC1?:string;
	  currC2?:string;
	  currC3?:string;
	  currC4?:string;
	  currC5?:string;
	  remarks ?:string;
	  createdBy ?:string;
	  createdDate ?:string;
	  modifiedBy ?:string;
	  modifiedDate ?:string;
	  bankingServiceNumber ?:string;
	  sellerOrgId ?:string;
	  sellerSubstationId ?:string;
	  sellerCompanyServiceId ?:string;
	  sellerCompanyServiceNumber ?:string;
	  sellerOrgName ?:string;
	  sellerSubstationName ?:string;
	  companyName ?:string;
	  month?:string;
	  year?:string;
}