export class Importsellers{

    generatorServiceNoOld?: string
    generatorServiceNoNew?: string
    companyName?: string
    edcName?: string
    mOrgId?: string
    genMakeNameOa?: string
    genMakeCode?: string
    noOfGenUnits?: string
    genUnitCapacity?: string
    totalCapacityKw?: string
    ptRatio?: string
    ctRatio?: string
    mf?: string
    sfNo?: string
    village?: string
    turbineSlNo?: string
    turbineRotorDia?: string
    turbineHubHe?: string
    ssNameInOa?: string
    mSubstationId?: string
    natureOfBoard?: string
    feederNameInOa?: string
    mFeederId?: string
    injectionVoltage?: string
    voltageCode?: string
    meterMake?: string
    meterMakeCode?: string
    meterNumber?: string
    isDlms?: string
    isAbt?: string
    isRec?: string
    wegGroupName?: string
    modemNo?: string
    purpose?: string
    commissionDateStr?: string
    accuracyClass?: string
    windPassName?: string
    remarks?: string
    imported?: string
    commisionDate?: Date
    windPassCode?: string
    wegGroupCode?: string
    importRemarks?: string
    cleanRec?: string
    fuel?: string
    fuelCode?: string
    surplusEnergy?: string
    acceleratedDepreciatio?: string
    flowTypeCode?: string

}