export class Oaa{
	id: string;
	buyerOrgId: string;
	buyerOrgName: string;
	buyerEndUtility: string;
	buyerCompServiceId: string;
	buyerCompServiceNumber: string;
	buyerCompanyName: string;
	buyerCompanyId: string;
	drawalTransSubstationId: string;
	drawalTransSubstationName: string;
	drawalTransVoltageCode: string;
	drawalTransVoltageDesc: string;
	drawalDistSubstationId: string;
	drawalDistSubstationName: string;
	drawalDistVoltageCode: string;
	drawalDistVoltageDesc: string;
	drawalFeederId: string;
	drawalFeederName: string;
	agreementPeriodCode: string;
	agreementPeriodDesc: string;
	periodDuration: string;
	proposedTotalUnits: string;
	approvedTotalUnits: string;
	c1Units: string;
	c2Units: string;
	c3Units: string;
	c4Units: string;
	c5Units: string;
	sellerOrgId: string;
	sellerOrgName: string;
	sellerEndUtility: string;
	sellerCompServiceId: string;
	sellerCompServiceNumber: string;
	sellerCompanyName: string;
	sellerCompanyId: string;
	sellerIsCaptive: string;
	injectionTransSubstationId: string;
	injectionTransSubstationName: string;
	injectionTransVoltageCode: string;
	injectionTransVoltageDesc: string;
	injectionDistSubstationId: string;
	injectionDistSubstationName: string;
	injectionDistVoltageCode: string;
	injectionDistVoltageDesc: string;
	injectionFeederId: string;
	injectionFeederName: string;
	paymentTypeCode: string;
	paymentTypeDesc: string;
	paymentBankDetails: string;
	paymentTxnNo: string;
	paymentDate: string;
	paymentAmount: string;
	appliedDate: string;
	approvedDate: string;
	statusCode: string;
	statusDesc: string;
	oaaNumber: string;
	oaaAppNumber: string;
	remarks: string;
	createdBy: string;
	createdDate: string;
	modifiedBy: string;
	modifiedDate: string;
	tEsIntentId: string;
	licensee: string;
	fromDate: string;
	toDate: string;
	agreementDate?:string;
	peakUnits?:string;
	offPeakUnits?:string;
	intervalTypeCode?:string;
	sharePercent?:string;
	sellerCapacity?:string;

	esIntentCode?:string;
	flowTypeCode?:string;
	flowTypeName?:string;
	constructor(){
		this.c1Units="0";
		this.c2Units="0";
		this.c3Units="0";
		this.c4Units="0";
		this.c5Units="0";
		this.peakUnits="0";
		this.offPeakUnits="0";
		this.sharePercent="0";
		
	}
}
