-- OPENACCESS.NAME_CHANGE_HIS definition

CREATE TABLE "OPENACCESS"."NAME_CHANGE_HIS" 
   (	"M_COMPANY_SERV_ID" VARCHAR2(100), 
	"M_COMP_SERVICE_NO" VARCHAR2(100), 
	"NC_MONTH" VARCHAR2(100), 
	"NC_YEAR" VARCHAR2(100), 
	"OLD_NAME" VARCHAR2(100), 
	"NEW_NAME" VARCHAR2(100)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;


  -- OPENACCESS.M_TRADE_HIS definition

CREATE TABLE "OPENACCESS"."M_TRADE_HIS" 
   (	"M_COMPANY_SERV_ID" VARCHAR2(100), 
	"TRD_MONTH" VARCHAR2(100), 
	"TRD_YEAR" VARCHAR2(100), 
	"ADDED_BUYER_COM_SERV_NUMBER" VARCHAR2(100), 
	"DELETED_BUYER_COMP_SERV_NUMBER" VARCHAR2(100), 
	"M_COMP_SERVICE_NO" VARCHAR2(100), 
	"ADDED_BUYER_NAME" VARCHAR2(100), 
	"ADDED_BUYER_SERV_NO" VARCHAR2(100), 
	"DELETED_BUYER_NAME" VARCHAR2(100), 
	"DELETED_BUYER_SERV_NO" VARCHAR2(100)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;


  -- OPENACCESS.SERVICE_MIGRATION_HIS definition

CREATE TABLE "OPENACCESS"."SERVICE_MIGRATION_HIS" 
   (	"M_COMPANY_SERV_ID" VARCHAR2(100), 
	"M_COMP_SERVICE_NO" VARCHAR2(100), 
	"MG_MONTH" VARCHAR2(100), 
	"MG_YEAR" VARCHAR2(100), 
	"MG_FROM" VARCHAR2(100), 
	"MG_TO" VARCHAR2(100)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;


  -- OPENACCESS.TEMP_SERVICE_HISTORY definition

CREATE TABLE "OPENACCESS"."TEMP_SERVICE_HISTORY" 
   (	"ID" VARCHAR2(1000), 
	"M_COMPANY_ID" VARCHAR2(1000), 
	"M_COMP_SERV_NUMBER" VARCHAR2(1000), 
	"M_COMPANY_NAME" VARCHAR2(1000), 
	"M_ORG_NAME" VARCHAR2(1000), 
	"FLOW_TYPE_CODE" VARCHAR2(1000), 
	"FUEL_TYPE_CODE" VARCHAR2(1000), 
	"OLD_NAME" VARCHAR2(1000), 
	"NEW_NAME" VARCHAR2(1000), 
	"NAME_CHANGE_MONTH" VARCHAR2(1000), 
	"NAME_CHANGE_YEAR" VARCHAR2(1000), 
	"MIGRATED_FROM" VARCHAR2(1000), 
	"MIGRATED_TO" VARCHAR2(1000), 
	"MIGRATION_MONTH" VARCHAR2(1000), 
	"MIGRATION_YEAR" VARCHAR2(1000), 
	"ADDED_BUYER_NAME" VARCHAR2(1000), 
	"ADDED_BUYER_SERVICE_NO" VARCHAR2(1000), 
	"ADDED_BUYER_M_COMPANY_ID" VARCHAR2(1000), 
	"COMMERCIAL_MONTH" VARCHAR2(1000), 
	"COMMERCIAL_YEAR" VARCHAR2(1000), 
	"REMOVED_BUYER_NAME" VARCHAR2(1000), 
	"REMOVED_BUYER_SERVICE_NO" VARCHAR2(1000), 
	"REMOVED_BUYER_M_COMPANY_ID" VARCHAR2(1000), 
	"OLD_METER_NO" VARCHAR2(100), 
	"NEW_METER_NO" VARCHAR2(100), 
	"MC_MONTH" VARCHAR2(100), 
	"MC_YEAR" VARCHAR2(100)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

  -- OPENACCESS.V_SERVICE_HISTORY source

CREATE OR REPLACE FORCE EDITIONABLE VIEW "OPENACCESS"."V_SERVICE_HISTORY" ("ID", "M_COMPANY_ID", "M_COMP_SERV_NUMBER", "M_COMPANY_NAME", "M_ORG_NAME", "FLOW_TYPE_CODE", "FUEL_TYPE_CODE", "OLD_NAME", "NEW_NAME", "NAME_CHANGE_MONTH", "NAME_CHANGE_YEAR", "MIGRATED_FROM", "MIGRATED_TO", "MIGRATION_MONTH", "MIGRATION_YEAR", "ADDED_BUYER_NAME", "ADDED_BUYER_SERVICE_NO", "ADDED_BUYER_M_COMPANY_ID", "COMMERCIAL_MONTH", "COMMERCIAL_YEAR", "REMOVED_BUYER_NAME", "REMOVED_BUYER_SERVICE_NO", "REMOVED_BUYER_M_COMPANY_ID", "OLD_METER_NO", "NEW_METER_NO", "MC_MONTH", "MC_YEAR") AS 
  SELECT ID, M_COMPANY_ID, M_COMP_SERV_NUMBER, M_COMPANY_NAME, M_ORG_NAME, FLOW_TYPE_CODE, FUEL_TYPE_CODE, OLD_NAME, NEW_NAME, NAME_CHANGE_MONTH, NAME_CHANGE_YEAR, MIGRATED_FROM, MIGRATED_TO, MIGRATION_MONTH, MIGRATION_YEAR, ADDED_BUYER_NAME, ADDED_BUYER_SERVICE_NO, ADDED_BUYER_M_COMPANY_ID, COMMERCIAL_MONTH, COMMERCIAL_YEAR, REMOVED_BUYER_NAME, REMOVED_BUYER_SERVICE_NO, REMOVED_BUYER_M_COMPANY_ID, OLD_METER_NO, NEW_METER_NO, MC_MONTH, MC_YEAR
FROM OPENACCESS.TEMP_SERVICE_HISTORY;