--------------------------------------------------------
--  File created - Monday-April-09-2018   
--------------------------------------------------------
DROP FUNCTION "OPENACCESS"."DELETE_ALL_MASTER_RECORDS";
--------------------------------------------------------
--  DDL for View V_COMPANY_SERVICE
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "OPENACCESS"."V_COMPANY_SERVICE" ("ID", "COMP_SER_TYPE_CODE", "COMP_SER_TYPE_NAME", "number", "M_COMPANY_ID", "M_COMPANY_CODE", "M_COMPANY_NAME", "COMPANY_IS_INTERNAL", "M_ORG_ID", "M_ORG_CODE", "M_ORG_NAME", "CAPACITY", "M_SUBSTATION_ID", "M_SUBSTATION_CODE", "M_SUBSTATION_NAME", "M_FEEDER_ID", "M_FEEDER_CODE", "M_FEEDER_NAME", "REF_NUMBER", "VOLTAGE_CODE", "VOLTAGE_NAME", "TARIFF", "ENABLED", "BANKING_SERVICE_ID", "BANKING_SERVICE_NUMBER", "DL_SERVICE_ID", "DL_SERVICE_NUMBER", "TL_SERVICE_ID", "TL_SERVICE_NUMBER", "UNADJUSTED_SERVICE_ID", "UNADJUSTED_SERVICE_NUMBER", "M_COMPANY_METER_ID", "MODEM_NUMBER", "METER_NUMBER", "MF", "ACCURACY_CLASS_CODE", "IS_ABTMETER", "METER_MAKE_CODE", "FUEL_TYPE_CODE", "FUEL_TYPE_NAME", "METER_CT1", "METER_CT2", "METER_CT3", "METER_PT1", "METER_PT2", "METER_PT3") AS 
  select companyservice.id,companyservice.COMP_SER_TYPE_CODE, typecodes.value_desc as COMP_SER_TYPE_NAME,companyservice."number",companyservice.m_company_id,company.code as M_COMPANY_CODE,company.name AS M_COMPANY_NAME,company.IS_INTERNAL AS COMPANY_IS_INTERNAL,companyservice.m_org_id,
					org.code as M_ORG_CODE, org.name as M_ORG_NAME,companyservice.capacity,
					companyservice.m_substation_id,substation.code as M_SUBSTATION_CODE,substation.name as M_SUBSTATION_NAME,companyservice.m_feeder_id,feeder.code as M_FEEDER_CODE,feeder.name as M_FEEDER_NAME,companyservice.ref_number,companyservice.voltage_code,voltagecodes.VALUE_DESC as VOLTAGE_NAME,companyservice.tariff,companyservice.enabled,
					companyservice.BANKING_SERVICE_ID, companyservice.BANKING_SERVICE_NUMBER, companyservice.DL_SERVICE_ID, companyservice.DL_SERVICE_NUMBER, companyservice.TL_SERVICE_ID, companyservice.TL_SERVICE_NUMBER,companyservice.UNADJUSTED_SERVICE_ID, companyservice.UNADJUSTED_SERVICE_NUMBER,
					companymeter.id AS M_COMPANY_METER_ID, companymeter.MODEM_NUMBER, companymeter.METER_NUMBER, companymeter.MF, companymeter.ACCURACY_CLASS_CODE, companymeter.IS_ABTMETER, companymeter.METER_MAKE_CODE,powerplant.FUEL_TYPE_CODE,fueltypecodes.VALUE_DESC as FUEL_TYPE_NAME,companymeter.METER_CT1,companymeter.METER_CT2,companymeter.METER_CT3,companymeter.METER_PT1,companymeter.METER_PT2,companymeter.METER_PT3
					from OPENACCESS.m_company_service companyservice  
					left join OPENACCESS.m_company company on company.id =companyservice.M_COMPANY_ID
					left join OPENACCESS.M_COMPANY_METER companymeter on companymeter.M_COMPANY_SERVICE_ID =companyservice.id
					left join OPENACCESS.m_org org on org.id=companyservice.M_ORG_ID
					left join OPENACCESS.m_substation substation on substation.id = companyservice.M_SUBSTATION_ID 
					left join OPENACCESS.m_feeder feeder on feeder.id = companyservice.M_FEEDER_ID 
					left join OPENACCESS.v_codes voltagecodes on companyservice.VOLTAGE_Code= voltagecodes.Value_Code AND  voltagecodes.list_code = 'VOLTAGE_CODE'
					left join OPENACCESS.v_codes typecodes on companyservice.COMP_SER_TYPE_CODE = typecodes.value_code and typecodes.list_code='SERVICE_TYPE_CODE'
                    left join OPENACCESS.M_POWERPLANT powerplant on  powerplant.M_SERVICE_ID=companyservice.id
                    left join OPENACCESS.v_codes fueltypecodes on powerplant.FUEL_TYPE_CODE= fueltypecodes.Value_Code AND  fueltypecodes.list_code = 'FUEL_TYPE_CODE'
;
--------------------------------------------------------
--  DDL for Table F_AGREEMENT
--------------------------------------------------------

  CREATE TABLE "OPENACCESS"."F_AGREEMENT" 
   (	"ID" VARCHAR2(50 BYTE), 
	"CODE" VARCHAR2(50 BYTE), 
	"SELLER_COMP_SERV_ID" VARCHAR2(50 BYTE), 
	"AGMT_VERSION" VARCHAR2(50 BYTE), 
	"SELLER_EDC_ID" VARCHAR2(50 BYTE), 
	"SELLER_COMPANY_ID" VARCHAR2(50 BYTE), 
	"AGREEMENT_DATE" DATE, 
	"IS_ACTIVE" CHAR(1 BYTE), 
	"FROM_DATE" DATE, 
	"TO_DATE" DATE, 
	"TOTAL_UNITS" VARCHAR2(50 BYTE), 
	"C1" VARCHAR2(50 BYTE), 
	"C2" VARCHAR2(50 BYTE), 
	"C3" VARCHAR2(50 BYTE), 
	"C4" VARCHAR2(50 BYTE), 
	"C5" VARCHAR2(50 BYTE), 
	"PEAK_UNITS" VARCHAR2(50 BYTE), 
	"OFF_PEAK_UNITS" VARCHAR2(50 BYTE), 
	"SIGNATORY_PARTY1" VARCHAR2(1500 BYTE), 
	"SIGNATORY_PARTY2" VARCHAR2(1500 BYTE), 
	"SIGNATORY_PARTY3" VARCHAR2(1500 BYTE), 
	"HAS_LINES" VARCHAR2(50 BYTE), 
	"CREATED_BY" VARCHAR2(50 BYTE), 
	"CREATED_DATE" DATE DEFAULT sysdate, 
	"ENABLED" CHAR(1 BYTE) DEFAULT 'Y', 
	"FROM_MONTH" VARCHAR2(50 BYTE), 
	"TO_YEAR" VARCHAR2(50 BYTE), 
	"FROM_YEAR" VARCHAR2(50 BYTE), 
	"TO_MONTH" VARCHAR2(50 BYTE), 
	"MODIFIED_DATE" DATE, 
	"MODIFIDED_BY" VARCHAR2(50 BYTE), 
	"BUYER_COMP_SERV_ID" VARCHAR2(50 BYTE), 
	"VERSION_CHANGE_REASON_CODE" VARCHAR2(50 BYTE), 
	"BUYER_EDC_ID" VARCHAR2(50 BYTE), 
	"BUYER_COMP_ID" VARCHAR2(50 BYTE), 
	"SUBSTATION_ID" VARCHAR2(50 BYTE), 
	"FEEDER_ID" VARCHAR2(50 BYTE), 
	"AGREEMENT_PERIOD_CODE" VARCHAR2(50 BYTE), 
	"FLOW_TYPE" VARCHAR2(50 BYTE), 
	"IS_LATEST" CHAR(1 BYTE), 
	"INTERVAL_TYPE_CODE" VARCHAR2(100 BYTE), 
	"SHARE_PERCENTAGE" FLOAT(126), 
	"IS_CAPTIVE" CHAR(1 BYTE), 
	"STATUS_CODE" VARCHAR2(50 BYTE), 
	"T_ES_INTENT_ID" VARCHAR2(50 BYTE), 
	"T_EWA_ID" VARCHAR2(50 BYTE), 
	"T_OAA_ID" VARCHAR2(50 BYTE), 
	"T_NOC_GENERATOR_ID" VARCHAR2(50 BYTE), 
	"T_INPRINCIPLE_APPLN_ID" VARCHAR2(50 BYTE), 
	"T_EPA_ID" VARCHAR2(50 BYTE), 
	"T_CS_ID" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table F_AGREEMENT_LINE
--------------------------------------------------------

  CREATE TABLE "OPENACCESS"."F_AGREEMENT_LINE" 
   (	"ID" VARCHAR2(50 BYTE), 
	"CODE" VARCHAR2(50 BYTE), 
	"F_AGREEMENT_ID" VARCHAR2(50 BYTE), 
	"BUYER_COMP_SERV_ID" VARCHAR2(50 BYTE), 
	"BUYER_ORG_ID" VARCHAR2(50 BYTE), 
	"BUYER_SUBSTATION_ID" VARCHAR2(50 BYTE), 
	"BUYER_FEEDER_ID" VARCHAR2(50 BYTE), 
	"DRAWAL_VOLTAGE_CODE" VARCHAR2(50 BYTE), 
	"PROPOSED_CAPACITY" VARCHAR2(50 BYTE), 
	"APPROVED_CAPACITY" VARCHAR2(50 BYTE), 
	"AGMT_PERIOD_CODE" VARCHAR2(50 BYTE), 
	"FLOW_TYPE_CODE" VARCHAR2(50 BYTE), 
	"FROM_DT" DATE, 
	"TO_DT" DATE, 
	"FROM_MONTH" VARCHAR2(50 BYTE), 
	"TO_YEAR" VARCHAR2(50 BYTE), 
	"FROM_YEAR" VARCHAR2(50 BYTE), 
	"TO_MONTH" VARCHAR2(50 BYTE), 
	"APPLIED_DT" DATE, 
	"APPROVED_DT" DATE, 
	"AGREEMENT_DT" DATE, 
	"IS_CAPTIVE" CHAR(1 BYTE), 
	"INTERVAL_TYPE_CODE" VARCHAR2(50 BYTE), 
	"C1" VARCHAR2(50 BYTE), 
	"C2" VARCHAR2(50 BYTE), 
	"C3" VARCHAR2(50 BYTE), 
	"C4" VARCHAR2(50 BYTE), 
	"C5" VARCHAR2(50 BYTE), 
	"PEAK_UNITS" VARCHAR2(50 BYTE), 
	"OFF_PEAK_UNITS" VARCHAR2(50 BYTE), 
	"SHARE_PERCENTAGE" VARCHAR2(50 BYTE), 
	"PAYMENT_TYPE_CODE" VARCHAR2(50 BYTE), 
	"PAYMENT_BANK_DETAILS" VARCHAR2(50 BYTE), 
	"PAYMENT_TXN_NO" VARCHAR2(50 BYTE), 
	"PAYMENT_DATE" DATE, 
	"PAYMENT_AMOUNT" VARCHAR2(50 BYTE), 
	"LICENSEE" VARCHAR2(50 BYTE), 
	"STATE_TRANS_LOSS" VARCHAR2(50 BYTE), 
	"STATE_TRANS_LOSS_PERCENT" VARCHAR2(50 BYTE), 
	"STATE_TRANS_CHARGES" VARCHAR2(50 BYTE), 
	"STATE_TRANS_CHARGES_PERCENT" VARCHAR2(50 BYTE), 
	"SCHEDULING_CHARGES" VARCHAR2(50 BYTE), 
	"SCHEDULING_CHARGES_PERCENT" VARCHAR2(50 BYTE), 
	"SYSTEM_OPR_CHARGES" VARCHAR2(50 BYTE), 
	"SYSTEM_OPR_CHARGES_PERCENT" VARCHAR2(50 BYTE), 
	"T_ES_INTENT_LINE_ID" VARCHAR2(50 BYTE), 
	"T_NOC_ID" VARCHAR2(50 BYTE), 
	"T_CONSENT_ID" VARCHAR2(50 BYTE), 
	"T_EWA_LINE_ID" VARCHAR2(50 BYTE), 
	"T_INPRINCIPLE_APPLN_LINE_ID" VARCHAR2(50 BYTE), 
	"T_NOC_GENERATOR_LINE_ID" VARCHAR2(50 BYTE), 
	"T_STANDING_CLEARENCE_ID" VARCHAR2(50 BYTE), 
	"CREATED_BY" VARCHAR2(50 BYTE), 
	"CREATED_DATE" DATE DEFAULT sysdate, 
	"ENABLED" CHAR(1 BYTE) DEFAULT 'Y', 
	"MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(50 BYTE), 
	"STATUS_CODE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table M_COMPANY
--------------------------------------------------------

  CREATE TABLE "OPENACCESS"."M_COMPANY" 
   (	"ID" VARCHAR2(50 BYTE), 
	"CODE" VARCHAR2(50 BYTE), 
	"NAME" VARCHAR2(100 BYTE), 
	"COMPANY_TYPE_CODE" VARCHAR2(50 BYTE), 
	"REGISTRATION_NO" VARCHAR2(50 BYTE), 
	"REGISTRATION_DATE" DATE, 
	"COB_DATE" DATE, 
	"INCORP_PLACE" VARCHAR2(50 BYTE), 
	"IS_CAPTIVE" VARCHAR2(25 BYTE), 
	"CAPTIVE_PURPOSE" VARCHAR2(100 BYTE), 
	"PAN" VARCHAR2(50 BYTE), 
	"TAN" VARCHAR2(50 BYTE), 
	"CST" VARCHAR2(50 BYTE), 
	"GST" VARCHAR2(50 BYTE), 
	"ENABLED" CHAR(1 BYTE) DEFAULT 'Y', 
	"CREATED_BY" VARCHAR2(50 BYTE), 
	"CREATED_DATE" DATE DEFAULT sysdate, 
	"MODIFIED_BY" VARCHAR2(50 BYTE), 
	"MODIFIED_DATE" DATE, 
	"REMARKS" VARCHAR2(300 BYTE), 
	"TYPE" VARCHAR2(100 BYTE), 
	"IS_INTERNAL" CHAR(1 BYTE), 
	"BANKING_SERVICE_ID" VARCHAR2(100 BYTE), 
	"UNADJUSTED_SERVICE_ID" VARCHAR2(100 BYTE), 
	"BANKING_SERVICE_NUMBER" VARCHAR2(100 BYTE), 
	"UNADJUSTED_SERVICE_NUMBER" VARCHAR2(100 BYTE), 
	"IS_BUYER" CHAR(1 BYTE), 
	"IS_SELLER" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table M_COMPANY_METER
--------------------------------------------------------

  CREATE TABLE "OPENACCESS"."M_COMPANY_METER" 
   (	"ID" VARCHAR2(50 BYTE), 
	"M_COMPANY_SERVICE_ID" VARCHAR2(50 BYTE), 
	"METER_NUMBER" VARCHAR2(100 BYTE), 
	"METER_MAKE_CODE" VARCHAR2(50 BYTE), 
	"ACCURACY_CLASS_CODE" VARCHAR2(50 BYTE), 
	"IS_ABTMETER" CHAR(1 BYTE), 
	"MF" VARCHAR2(50 BYTE), 
	"REMARKS" VARCHAR2(300 BYTE), 
	"CREATED_BY" VARCHAR2(50 BYTE), 
	"CREATED_DATE" DATE DEFAULT sysdate, 
	"MODIFIED_BY" VARCHAR2(50 BYTE), 
	"MODIFIED_DATE" DATE, 
	"MODEM_NUMBER" VARCHAR2(100 BYTE), 
	"ENABLED" CHAR(1 BYTE) DEFAULT 'Y', 
	"METER_CT1" VARCHAR2(50 BYTE), 
	"METER_CT2" VARCHAR2(50 BYTE), 
	"METER_CT3" VARCHAR2(50 BYTE), 
	"METER_PT1" VARCHAR2(50 BYTE), 
	"METER_PT2" VARCHAR2(50 BYTE), 
	"METER_PT3" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table M_COMPANY_SERVICE
--------------------------------------------------------

  CREATE TABLE "OPENACCESS"."M_COMPANY_SERVICE" 
   (	"ID" VARCHAR2(50 BYTE), 
	"COMP_SER_TYPE_CODE" VARCHAR2(25 BYTE), 
	"number" VARCHAR2(50 BYTE), 
	"M_COMPANY_ID" VARCHAR2(50 BYTE), 
	"M_ORG_ID" VARCHAR2(50 BYTE), 
	"CAPACITY" VARCHAR2(50 BYTE), 
	"M_SUBSTATION_ID" VARCHAR2(50 BYTE), 
	"M_FEEDER_ID" VARCHAR2(50 BYTE), 
	"REF_NUMBER" VARCHAR2(50 BYTE), 
	"VOLTAGE_CODE" VARCHAR2(50 BYTE), 
	"TARIFF" VARCHAR2(50 BYTE), 
	"TOTAL_CAPACITY" VARCHAR2(50 BYTE), 
	"ENABLED" CHAR(1 BYTE) DEFAULT 'Y', 
	"REMARKS" VARCHAR2(300 BYTE), 
	"CREATED_BY" VARCHAR2(50 BYTE), 
	"CREATED_DATE" DATE DEFAULT sysdate, 
	"MODIFIED_BY" VARCHAR2(50 BYTE), 
	"MODIFIED_DATE" DATE, 
	"TYPE" VARCHAR2(100 BYTE), 
	"BANKING_SERVICE_ID" VARCHAR2(100 BYTE), 
	"BANKING_SERVICE_NUMBER" VARCHAR2(100 BYTE), 
	"TL_SERVICE_ID" VARCHAR2(100 BYTE), 
	"TL_SERVICE_NUMBER" VARCHAR2(100 BYTE), 
	"DL_SERVICE_ID" VARCHAR2(100 BYTE), 
	"DL_SERVICE_NUMBER" VARCHAR2(100 BYTE), 
	"UNADJUSTED_SERVICE_ID" VARCHAR2(100 BYTE), 
	"UNADJUSTED_SERVICE_NUMBER" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table M_COMPANY_SHAREHOLDER
--------------------------------------------------------

  CREATE TABLE "OPENACCESS"."M_COMPANY_SHAREHOLDER" 
   (	"ID" VARCHAR2(50 BYTE), 
	"M_COMPANY_ID" VARCHAR2(50 BYTE), 
	"M_SHAREHOLDER_COMPANY_ID" VARCHAR2(50 BYTE), 
	"share" VARCHAR2(25 BYTE), 
	"MEASURE" VARCHAR2(50 BYTE), 
	"ENABLED" CHAR(1 BYTE) DEFAULT 'Y', 
	"REMARKS" VARCHAR2(300 BYTE), 
	"CREATED_BY" VARCHAR2(50 BYTE), 
	"CREATED_DATE" DATE DEFAULT sysdate, 
	"MODIFIED_BY" VARCHAR2(50 BYTE), 
	"MODIFIED_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table M_GENERATOR
--------------------------------------------------------

  CREATE TABLE "OPENACCESS"."M_GENERATOR" 
   (	"ID" VARCHAR2(50 BYTE), 
	"M_POWERPLANT_ID" VARCHAR2(50 BYTE), 
	"NAME" VARCHAR2(100 BYTE), 
	"MAKE_CODE" VARCHAR2(50 BYTE), 
	"SERIAL_NO" VARCHAR2(1000 BYTE), 
	"ROTOR_DIA" VARCHAR2(25 BYTE), 
	"HUB_HEIGHT" VARCHAR2(25 BYTE), 
	"CAPACITY" VARCHAR2(25 BYTE), 
	"REFERENCE_ID" VARCHAR2(50 BYTE), 
	"VOLTAGE_CODE" VARCHAR2(25 BYTE), 
	"ENABLED" CHAR(1 BYTE) DEFAULT 'Y', 
	"REMARKS" VARCHAR2(300 BYTE), 
	"CREATED_BY" VARCHAR2(50 BYTE), 
	"CREATED_DATE" DATE DEFAULT sysdate, 
	"MODIFIED_BY" VARCHAR2(50 BYTE), 
	"MODIFIED_DATE" DATE, 
	"NO_OF_UNITS" VARCHAR2(25 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table M_POWERPLANT
--------------------------------------------------------

  CREATE TABLE "OPENACCESS"."M_POWERPLANT" 
   (	"ID" VARCHAR2(50 BYTE), 
	"IS_PRIMARY" CHAR(1 BYTE), 
	"VERSION" NUMBER(2,0), 
	"CODE" VARCHAR2(50 BYTE), 
	"NAME" VARCHAR2(100 BYTE), 
	"PLANT_TYPE_CODE" VARCHAR2(50 BYTE), 
	"FUEL_TYPE_CODE" VARCHAR2(50 BYTE), 
	"M_SERVICE_ID" VARCHAR2(50 BYTE), 
	"M_ORG_ID" VARCHAR2(50 BYTE), 
	"T_GRID_CONN_APPLN_ID" VARCHAR2(50 BYTE), 
	"TOTAL_CAPACITY" VARCHAR2(25 BYTE), 
	"M_SUBSTATION_ID" VARCHAR2(50 BYTE), 
	"INTERFACE_VOLTAGE_PHASE" VARCHAR2(25 BYTE), 
	"INTERFACE_VOLTAGE_FREQUENCY" VARCHAR2(25 BYTE), 
	"COMMISSION_DATE" DATE, 
	"PURPOSE" VARCHAR2(500 BYTE), 
	"ENABLED" CHAR(1 BYTE) DEFAULT 'Y', 
	"STATUS" VARCHAR2(25 BYTE), 
	"LINE1" VARCHAR2(100 BYTE), 
	"CITY" VARCHAR2(50 BYTE), 
	"STATE_CODE" VARCHAR2(50 BYTE), 
	"PINCODE" VARCHAR2(50 BYTE), 
	"VILLAGE" VARCHAR2(50 BYTE), 
	"TALUK_CODE" VARCHAR2(50 BYTE), 
	"DISTRICT_CODE" VARCHAR2(50 BYTE), 
	"PLS_SF_NO" VARCHAR2(50 BYTE), 
	"PL_VILLAGE" VARCHAR2(50 BYTE), 
	"PL_TOWN" VARCHAR2(50 BYTE), 
	"PL_TALUK_CODE" VARCHAR2(50 BYTE), 
	"PL_DISTRICT_CODE" VARCHAR2(50 BYTE), 
	"WIND_PASS_CODE" VARCHAR2(50 BYTE), 
	"WIND_ZONE_AREA_CODE" VARCHAR2(50 BYTE), 
	"APPLICATION_DT" DATE, 
	"APPROVAL_DT" DATE, 
	"REMARKS" VARCHAR2(300 BYTE), 
	"CREATED_BY" VARCHAR2(50 BYTE), 
	"CREATED_DATE" DATE DEFAULT sysdate, 
	"MODIFIED_BY" VARCHAR2(50 BYTE), 
	"MODIFIED_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table M_SIGNUP
--------------------------------------------------------

  CREATE TABLE "OPENACCESS"."M_SIGNUP" 
   (	"ID" VARCHAR2(50 BYTE), 
	"COMPANY_NAME" VARCHAR2(100 BYTE), 
	"PURPOSE" VARCHAR2(50 BYTE), 
	"REGISTRATION_NO" VARCHAR2(50 BYTE), 
	"REGISTRATION_DATE" DATE, 
	"COMMISSION_DATE" DATE, 
	"VOLTAGE" VARCHAR2(50 BYTE), 
	"HTSC_NUMBER_OLD" VARCHAR2(100 BYTE), 
	"TARIFF" VARCHAR2(50 BYTE), 
	"SANCTIONED_QUANTUM" VARCHAR2(25 BYTE), 
	"TOTAL_CAPACITY" VARCHAR2(25 BYTE), 
	"IS_CAPTIVE" CHAR(1 BYTE), 
	"USER_NAME" VARCHAR2(100 BYTE), 
	"USER_ID" VARCHAR2(100 BYTE), 
	"PASSWORD" VARCHAR2(100 BYTE), 
	"POWERPLANT_TYPE" VARCHAR2(50 BYTE), 
	"POWERPLANT_NAME" VARCHAR2(100 BYTE), 
	"FUEL" VARCHAR2(50 BYTE), 
	"NO_OF_GENERATOR" NUMBER(2,0), 
	"GENERATOR_TYPE" VARCHAR2(50 BYTE), 
	"GENERATOR_MODEL" VARCHAR2(50 BYTE), 
	"IS_REC" CHAR(1 BYTE), 
	"WIND_PASS_CODE" VARCHAR2(50 BYTE), 
	"LOCATION" VARCHAR2(500 BYTE), 
	"ADDRESS_LINE" VARCHAR2(500 BYTE), 
	"VILLAGE" VARCHAR2(100 BYTE), 
	"TALUK_CODE" VARCHAR2(50 BYTE), 
	"CITY" VARCHAR2(100 BYTE), 
	"DISTRICT_CODE" VARCHAR2(50 BYTE), 
	"STATE_CODE" VARCHAR2(50 BYTE), 
	"M_ORG_ID" VARCHAR2(50 BYTE), 
	"M_SUBSTATION_ID" VARCHAR2(50 BYTE), 
	"M_FEEDER_ID" VARCHAR2(50 BYTE), 
	"IS_COMPLETE" CHAR(1 BYTE), 
	"COMPANY_ADDRESS" VARCHAR2(1000 BYTE), 
	"APPROVAL_DT" DATE, 
	"PLANT_CLASS_TYPE_CODE" VARCHAR2(50 BYTE), 
	"BUYER_TYPE_CODE" VARCHAR2(50 BYTE), 
	"GENERATOR_CAPACITY" VARCHAR2(20 BYTE), 
	"METER_NUMBER" VARCHAR2(50 BYTE), 
	"METER_MAKE_CODE" VARCHAR2(50 BYTE), 
	"ACCURACY_CLASS_TYPE_CODE" VARCHAR2(50 BYTE), 
	"IS_ABT_METER" CHAR(1 BYTE), 
	"MULTIPLICATION_FACTOR" VARCHAR2(20 BYTE), 
	"APPLICATION_DT" DATE, 
	"CREATED_BY" VARCHAR2(50 BYTE), 
	"CREATED_DATE" DATE DEFAULT sysdate, 
	"MODIFIED_BY" VARCHAR2(50 BYTE), 
	"MODIFIED_DATE" DATE, 
	"REMARKS" VARCHAR2(300 BYTE), 
	"CONSUMER_HT_NUMBER" VARCHAR2(50 BYTE), 
	"TRADE_START_DATE" DATE, 
	"TRADE_END_DATE" DATE, 
	"TRADER_SERVICE_ID" VARCHAR2(50 BYTE), 
	"MODEM_NO" VARCHAR2(100 BYTE), 
	"GU_MODEL1" VARCHAR2(100 BYTE), 
	"GU_CAPACITY1" VARCHAR2(100 BYTE), 
	"NO_OF_GU1" VARCHAR2(100 BYTE), 
	"GU_MODEL2" VARCHAR2(100 BYTE), 
	"GU_CAPACITY2" VARCHAR2(100 BYTE), 
	"NO_OF_GU2" VARCHAR2(100 BYTE), 
	"GU_MODEL3" VARCHAR2(100 BYTE), 
	"GU_CAPACITY3" VARCHAR2(100 BYTE), 
	"NO_OF_GU3" VARCHAR2(100 BYTE), 
	"GU_MODEL4" VARCHAR2(100 BYTE), 
	"GU_CAPACITY4" VARCHAR2(100 BYTE), 
	"NO_OF_GU4" VARCHAR2(100 BYTE), 
	"GU_MODEL5" VARCHAR2(100 BYTE), 
	"GU_CAPACITY5" VARCHAR2(100 BYTE), 
	"NO_OF_GU5" VARCHAR2(100 BYTE), 
	"GU_MODEL6" VARCHAR2(100 BYTE), 
	"GU_CAPACITY6" VARCHAR2(100 BYTE), 
	"NO_OF_GU6" VARCHAR2(100 BYTE), 
	"METER_CT_1" VARCHAR2(100 BYTE), 
	"METER_CT_2" VARCHAR2(100 BYTE), 
	"METER_CT_3" VARCHAR2(100 BYTE), 
	"METER_BT_1" VARCHAR2(100 BYTE), 
	"METER_BT_2" VARCHAR2(100 BYTE), 
	"METER_BT_3" VARCHAR2(100 BYTE), 
	"SURPLUS_ENERGY_CODE" VARCHAR2(100 BYTE), 
	"ENABLED" CHAR(1 BYTE) DEFAULT 'Y', 
	"TOTAL_GENERATOR_UNIT" VARCHAR2(50 BYTE), 
	"METER_PT_RATIO" VARCHAR2(100 BYTE), 
	"METER_CT_RATIO" VARCHAR2(100 BYTE), 
	"TURBINE_SL_NO" VARCHAR2(100 BYTE), 
	"TURBINE_ROTOR_DIA" VARCHAR2(100 BYTE), 
	"TURBINE_HUB_HEIGHT" VARCHAR2(100 BYTE), 
	"IS_DLMS_METER" VARCHAR2(50 BYTE), 
	"HTSC_NUMBER" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table M_TRADE_RELATIONSHIP
--------------------------------------------------------

  CREATE TABLE "OPENACCESS"."M_TRADE_RELATIONSHIP" 
   (	"ID" VARCHAR2(50 BYTE), 
	"QUANTUM" VARCHAR2(50 BYTE), 
	"FROM_DATE" DATE, 
	"TO_DATE" DATE, 
	"STATUS_CODE" VARCHAR2(50 BYTE), 
	"M_SELLER_COMPANY_ID" VARCHAR2(50 BYTE), 
	"M_SELLER_COMP_SERVICE_ID" VARCHAR2(50 BYTE), 
	"M_BUYER_COMPANY_ID" VARCHAR2(50 BYTE), 
	"M_BUYER_COMP_SERVICE_ID" VARCHAR2(50 BYTE), 
	"REFERENCENUMBER" VARCHAR2(200 BYTE), 
	"REMARKS" VARCHAR2(300 BYTE), 
	"CREATED_BY" VARCHAR2(50 BYTE), 
	"CREATED_DATE" DATE DEFAULT sysdate, 
	"MODIFIED_BY" VARCHAR2(50 BYTE), 
	"MODIFIED_DATE" DATE, 
	"C1" VARCHAR2(50 BYTE), 
	"C2" VARCHAR2(50 BYTE), 
	"C3" VARCHAR2(50 BYTE), 
	"C4" VARCHAR2(50 BYTE), 
	"C5" VARCHAR2(50 BYTE), 
	"IS_CAPTIVE" CHAR(1 BYTE), 
	"ENABLED" CHAR(1 BYTE) DEFAULT 'Y', 
	"PEAK_UNITS" VARCHAR2(100 BYTE), 
	"OFF_PEAK_UNITS" VARCHAR2(100 BYTE), 
	"INTERVAL_TYPE_CODE" VARCHAR2(50 BYTE), 
	"SHARE_PERCENT" VARCHAR2(100 BYTE), 
	"TRADE_RELATIONSHIP_SOURCE_CODE" VARCHAR2(50 BYTE) DEFAULT 'OAA'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_COMPANY_METER_CHANGE
--------------------------------------------------------

  CREATE TABLE "OPENACCESS"."T_COMPANY_METER_CHANGE" 
   (	"ID" VARCHAR2(50 BYTE), 
	"CODE" VARCHAR2(50 BYTE), 
	"TYPE_OF_METER_CHANGE" VARCHAR2(50 BYTE), 
	"M_EDC_ID" VARCHAR2(50 BYTE), 
	"M_COMPANY_ID" VARCHAR2(50 BYTE), 
	"M_COMPANY_SERVICE_ID" VARCHAR2(50 BYTE), 
	"M_COMPANY_METER_ID" VARCHAR2(50 BYTE), 
	"METER_CHANGE_DATE" DATE, 
	"OLD_METER_NUMBER" VARCHAR2(100 BYTE), 
	"NEW_METER_NUMBER" VARCHAR2(100 BYTE), 
	"OLD_METER_MAKE_CODE" VARCHAR2(50 BYTE), 
	"NEW_METER_MAKE_CODE" VARCHAR2(50 BYTE), 
	"OLD_ACCURACY_CLASS_CODE" VARCHAR2(50 BYTE), 
	"NEW_ACCURACY_CLASS_CODE" VARCHAR2(50 BYTE), 
	"OLD_IS_ABTMETER" CHAR(1 BYTE), 
	"NEW_IS_ABTMETER" CHAR(1 BYTE), 
	"OLD_MF" VARCHAR2(50 BYTE), 
	"NEW_MF" VARCHAR2(50 BYTE), 
	"OLD_MODEM_NUMBER" VARCHAR2(100 BYTE), 
	"NEW_MODEM_NUMBER" VARCHAR2(100 BYTE), 
	"OLD_METER_CT1" VARCHAR2(50 BYTE), 
	"OLD_METER_CT2" VARCHAR2(50 BYTE), 
	"OLD_METER_CT3" VARCHAR2(50 BYTE), 
	"OLD_METER_PT1" VARCHAR2(50 BYTE), 
	"OLD_METER_PT2" VARCHAR2(50 BYTE), 
	"OLD_METER_PT3" VARCHAR2(50 BYTE), 
	"NEW_METER_CT1" VARCHAR2(50 BYTE), 
	"NEW_METER_CT2" VARCHAR2(50 BYTE), 
	"NEW_METER_CT3" VARCHAR2(50 BYTE), 
	"NEW_METER_PT1" VARCHAR2(50 BYTE), 
	"NEW_METER_PT2" VARCHAR2(50 BYTE), 
	"NEW_METER_PT3" VARCHAR2(50 BYTE), 
	"REMARKS" VARCHAR2(300 BYTE), 
	"CREATED_BY" VARCHAR2(50 BYTE), 
	"CREATED_DATE" DATE DEFAULT sysdate, 
	"MODIFIED_BY" VARCHAR2(50 BYTE), 
	"MODIFIED_DATE" DATE, 
	"ENABLED" CHAR(1 BYTE) DEFAULT 'Y', 
	"IS_METER_NUMBER_CHANGE" CHAR(1 BYTE), 
	"IS_METER_SET_CHANGE" CHAR(1 BYTE), 
	"IS_MODEM_NUMBER_CHANGE" CHAR(1 BYTE), 
	"STATUS_CODE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_COMPANY_NAME_CHANGE
--------------------------------------------------------

  CREATE TABLE "OPENACCESS"."T_COMPANY_NAME_CHANGE" 
   (	"ID" VARCHAR2(50 BYTE), 
	"CODE" VARCHAR2(50 BYTE), 
	"M_EDC_ID" VARCHAR2(50 BYTE), 
	"M_COMPANY_ID" VARCHAR2(50 BYTE), 
	"M_COMPANY_SERVICE_ID" VARCHAR2(50 BYTE), 
	"M_COMPANY_METER_ID" VARCHAR2(50 BYTE), 
	"COMPANY_NAME_CHANGE_DATE" DATE, 
	"OLD_COMPANY_NAME" VARCHAR2(100 BYTE), 
	"NEW_COMPANY_NAME" VARCHAR2(100 BYTE), 
	"REMARKS" VARCHAR2(300 BYTE), 
	"CREATED_BY" VARCHAR2(50 BYTE), 
	"CREATED_DATE" DATE DEFAULT sysdate, 
	"MODIFIED_BY" VARCHAR2(50 BYTE), 
	"MODIFIED_DATE" DATE, 
	"ENABLED" CHAR(1 BYTE) DEFAULT 'Y', 
	"STATUS_CODE" VARCHAR2(50 BYTE), 
	"FLOW_TYPE_CODE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_CONSENT
--------------------------------------------------------

  CREATE TABLE "OPENACCESS"."T_CONSENT" 
   (	"ID" VARCHAR2(50 BYTE), 
	"BUYER_COMP_SERV_ID" VARCHAR2(50 BYTE), 
	"BUYER_END_ORG_ID" VARCHAR2(100 BYTE), 
	"DRAWAL_SUBSTATION_ID" VARCHAR2(50 BYTE), 
	"DRAWAL_FEEDER_ID" VARCHAR2(50 BYTE), 
	"DRAWAL_VOLTAGE_CODE" VARCHAR2(50 BYTE), 
	"AGMT_PERIOD_CODE" VARCHAR2(50 BYTE), 
	"FROM_DT" DATE, 
	"TO_DT" DATE, 
	"T_NOC_ID" VARCHAR2(50 BYTE), 
	"PROPOSED_CAPACITY" VARCHAR2(50 BYTE), 
	"APPROVED_CAPACITY" VARCHAR2(50 BYTE), 
	"IS_ABT_INSTALLED" CHAR(1 BYTE), 
	"NO_ABT_REASON" VARCHAR2(500 BYTE), 
	"HAS_REAL_TIME_CON" CHAR(1 BYTE), 
	"SELLER_COMP_SERV_ID" VARCHAR2(50 BYTE), 
	"SELLER_END_ORG_ID" VARCHAR2(100 BYTE), 
	"INJECTION_SUBSTATION_ID" VARCHAR2(50 BYTE), 
	"INJECTION_FEEDER_ID" VARCHAR2(50 BYTE), 
	"INJECTION_VOLTAGE_CODE" VARCHAR2(50 BYTE), 
	"APPLIED_DT" DATE, 
	"APPROVED_DT" DATE, 
	"STATUS_CODE" VARCHAR2(50 BYTE), 
	"REMARKS" VARCHAR2(100 BYTE), 
	"CREATED_BY" VARCHAR2(50 BYTE), 
	"CREATED_DT" DATE, 
	"MODIFIED_BY" VARCHAR2(50 BYTE), 
	"MODIFIED_DT" DATE, 
	"T_ES_INTENT_ID" VARCHAR2(50 BYTE), 
	"AGREEMENT_DT" DATE, 
	"IS_CAPTIVE" CHAR(1 BYTE), 
	"CREATED_DATE" DATE DEFAULT sysdate, 
	"ENABLED" CHAR(1 BYTE) DEFAULT 'Y', 
	"CODE" VARCHAR2(50 BYTE), 
	"FLOW_TYPE_CODE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_CS
--------------------------------------------------------

  CREATE TABLE "OPENACCESS"."T_CS" 
   (	"ID" VARCHAR2(50 BYTE), 
	"CODE" VARCHAR2(50 BYTE), 
	"SELLER_COMP_SERV_ID" VARCHAR2(50 BYTE), 
	"SELLER_EDC_ID" VARCHAR2(50 BYTE), 
	"SELLER_COMPANY_ID" VARCHAR2(50 BYTE), 
	"AGREEMENT_DATE" DATE, 
	"EFFECTIVE_DATE" DATE, 
	"FROM_DATE" DATE, 
	"TO_DATE" DATE, 
	"CREATED_BY" VARCHAR2(50 BYTE), 
	"CREATED_DATE" DATE DEFAULT sysdate, 
	"ENABLED" CHAR(1 BYTE) DEFAULT 'Y', 
	"FROM_MONTH" VARCHAR2(50 BYTE), 
	"TO_YEAR" VARCHAR2(50 BYTE), 
	"FROM_YEAR" VARCHAR2(50 BYTE), 
	"TO_MONTH" VARCHAR2(50 BYTE), 
	"MODIFIED_DATE" DATE, 
	"MODIFIDED_BY" VARCHAR2(50 BYTE), 
	"AGREEMENT_PERIOD_CODE" VARCHAR2(50 BYTE), 
	"FLOW_TYPE_CODE" VARCHAR2(50 BYTE), 
	"STATUS_CODE" VARCHAR2(50 BYTE), 
	"ID_TOTAL_COST" VARCHAR2(50 BYTE), 
	"ID_TOTAL_CURRENCY" VARCHAR2(50 BYTE), 
	"ID_TOTAL_EXCHANGE_RATE" VARCHAR2(50 BYTE), 
	"APPROVED_CAPACITY" VARCHAR2(50 BYTE), 
	"VOLTAGE_CODE" VARCHAR2(50 BYTE), 
	"T_ES_INTENT_ID" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_CS_ID_TABLEA
--------------------------------------------------------

  CREATE TABLE "OPENACCESS"."T_CS_ID_TABLEA" 
   (	"ID" VARCHAR2(50 BYTE), 
	"T_CS_ID" VARCHAR2(50 BYTE), 
	"CLASS_OF_EQUTIY_SHARES" VARCHAR2(50 BYTE), 
	"NUMBER_OF_EQUTIY_SHARES" VARCHAR2(50 BYTE), 
	"VALUE_OF_EQUTIY_SHARES" VARCHAR2(50 BYTE), 
	"AMOUNT_OF_EQUTIY_SHARES" VARCHAR2(50 BYTE), 
	"NUMBER_OF_VOTING_RIGHTS" VARCHAR2(50 BYTE), 
	"PERCT_IN_EQUTIY_SHARES" VARCHAR2(50 BYTE), 
	"PERCT_IN_VOTING_RIGHTS" VARCHAR2(50 BYTE), 
	"PERCT_IN_VOTING_WITH_EQUITY" VARCHAR2(50 BYTE), 
	"REMARKS" VARCHAR2(300 BYTE), 
	"CREATED_BY" VARCHAR2(50 BYTE), 
	"CREATED_DATE" DATE DEFAULT sysdate, 
	"MODIFIED_BY" VARCHAR2(50 BYTE), 
	"MODIFIED_DATE" DATE, 
	"ENABLED" CHAR(1 BYTE) DEFAULT 'Y'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_CS_ID_TABLEB
--------------------------------------------------------

  CREATE TABLE "OPENACCESS"."T_CS_ID_TABLEB" 
   (	"ID" VARCHAR2(50 BYTE), 
	"T_CS_ID" VARCHAR2(50 BYTE), 
	"CLASS_OF_SHAREHOLDER" VARCHAR2(50 BYTE), 
	"NUMBER_OF_EQUTIY_SHARES" VARCHAR2(50 BYTE), 
	"VALUE_OF_EQUTIY_SHARES" VARCHAR2(50 BYTE), 
	"AMOUNT_OF_EQUTIY_SHARES" VARCHAR2(50 BYTE), 
	"NUMBER_OF_VOTING_RIGHTS" VARCHAR2(50 BYTE), 
	"PERCT_IN_EQUTIY_SHARES" VARCHAR2(50 BYTE), 
	"PERCT_IN_VOTING_RIGHTS" VARCHAR2(50 BYTE), 
	"PERCT_IN_VOTING_WITH_EQUITY" VARCHAR2(50 BYTE), 
	"REMARKS" VARCHAR2(300 BYTE), 
	"CREATED_BY" VARCHAR2(50 BYTE), 
	"CREATED_DATE" DATE DEFAULT sysdate, 
	"MODIFIED_BY" VARCHAR2(50 BYTE), 
	"MODIFIED_DATE" DATE, 
	"ENABLED" CHAR(1 BYTE) DEFAULT 'Y'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_CS_LOAN
--------------------------------------------------------

  CREATE TABLE "OPENACCESS"."T_CS_LOAN" 
   (	"ID" VARCHAR2(50 BYTE), 
	"T_CS_ID" VARCHAR2(50 BYTE), 
	"LOAN_ORIGIN" VARCHAR2(100 BYTE), 
	"SOURCE_NAME" VARCHAR2(50 BYTE), 
	"SOURCE_ADDRESS" VARCHAR2(50 BYTE), 
	"LOAN_AMOUNT" VARCHAR2(50 BYTE), 
	"CURRENCY" VARCHAR2(50 BYTE), 
	"EXCHANGE_RATE" VARCHAR2(50 BYTE), 
	"REMARKS" VARCHAR2(300 BYTE), 
	"CREATED_BY" VARCHAR2(50 BYTE), 
	"CREATED_DATE" DATE DEFAULT sysdate, 
	"MODIFIED_BY" VARCHAR2(50 BYTE), 
	"MODIFIED_DATE" DATE, 
	"ENABLED" CHAR(1 BYTE) DEFAULT 'Y'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_CS_QUANTUM_ALLOCATION
--------------------------------------------------------

  CREATE TABLE "OPENACCESS"."T_CS_QUANTUM_ALLOCATION" 
   (	"ID" VARCHAR2(50 BYTE), 
	"T_CS_ID" VARCHAR2(50 BYTE), 
	"BUYER_COMP_SERV_ID" VARCHAR2(50 BYTE), 
	"BUYER_ORG_ID" VARCHAR2(50 BYTE), 
	"CAPTIVE_COMPANY_NAME" VARCHAR2(50 BYTE), 
	"QUANTUM" VARCHAR2(50 BYTE), 
	"INJECTING_VOLTAGE_CODE" VARCHAR2(50 BYTE), 
	"DRAWAL_VOLTAGE_CODE" VARCHAR2(50 BYTE), 
	"REMARKS" VARCHAR2(300 BYTE), 
	"CREATED_BY" VARCHAR2(50 BYTE), 
	"CREATED_DATE" DATE DEFAULT sysdate, 
	"MODIFIED_BY" VARCHAR2(50 BYTE), 
	"MODIFIED_DATE" DATE, 
	"ENABLED" CHAR(1 BYTE) DEFAULT 'Y'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_EPA
--------------------------------------------------------

  CREATE TABLE "OPENACCESS"."T_EPA" 
   (	"ID" VARCHAR2(50 BYTE), 
	"SELLER_COMP_SERV_ID" VARCHAR2(50 BYTE), 
	"SELLER_END_ORG_ID" VARCHAR2(100 BYTE), 
	"AGMT_PERIOD_CODE" VARCHAR2(50 BYTE), 
	"FROM_DT" DATE, 
	"TO_DT" DATE, 
	"APPLIED_DT" DATE, 
	"APPROVED_DT" DATE, 
	"STATUS_CODE" VARCHAR2(50 BYTE), 
	"AGREEMENT_NUMBER" VARCHAR2(50 BYTE), 
	"EPA_APPROVAL_NUMBER" VARCHAR2(50 BYTE), 
	"REMARKS" VARCHAR2(100 BYTE), 
	"CREATED_BY" VARCHAR2(50 BYTE), 
	"MODIFIED_BY" VARCHAR2(50 BYTE), 
	"MODIFIED_DT" DATE, 
	"T_ES_INTENT_ID" VARCHAR2(50 BYTE), 
	"SELLER_IS_CAPTIVE" CHAR(1 BYTE), 
	"AGREEMENT_DT" DATE, 
	"PROPOSED_TOTAL_UNITS" VARCHAR2(100 BYTE), 
	"APPROVED_TOTAL_UNITS" VARCHAR2(100 BYTE), 
	"CREATED_DATE" DATE DEFAULT sysdate, 
	"ENABLED" CHAR(1 BYTE) DEFAULT 'Y', 
	"CODE" VARCHAR2(50 BYTE), 
	"C1" VARCHAR2(50 BYTE), 
	"C2" VARCHAR2(50 BYTE), 
	"C3" VARCHAR2(50 BYTE), 
	"C4" VARCHAR2(50 BYTE), 
	"C5" VARCHAR2(50 BYTE), 
	"PEAK_UNITS" VARCHAR2(50 BYTE), 
	"OFF_PEAK_UNITS" VARCHAR2(50 BYTE), 
	"FROM_MONTH" VARCHAR2(50 BYTE), 
	"TO_YEAR" VARCHAR2(50 BYTE), 
	"FROM_YEAR" VARCHAR2(50 BYTE), 
	"TO_MONTH" VARCHAR2(50 BYTE), 
	"BUYER_COMP_SERV_ID" VARCHAR2(50 BYTE), 
	"FLOW_TYPE_CODE" VARCHAR2(50 BYTE), 
	"INTERVAL_TYPE_CODE" VARCHAR2(100 BYTE), 
	"SHARE_PERCENTAGE" FLOAT(126), 
	"VOLTAGE_CODE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_EPA_LINES
--------------------------------------------------------

  CREATE TABLE "OPENACCESS"."T_EPA_LINES" 
   (	"ID" VARCHAR2(50 BYTE), 
	"T_EPA_ID" VARCHAR2(50 BYTE), 
	"REMARKS" VARCHAR2(100 BYTE), 
	"CREATED_BY" VARCHAR2(50 BYTE), 
	"CREATED_DT" DATE, 
	"MODIFIED_BY" VARCHAR2(50 BYTE), 
	"MODIFIED_DT" DATE, 
	"M_GENERATOR_ID" VARCHAR2(50 BYTE), 
	"PROPOSED_TOTAL_UNITS" VARCHAR2(50 BYTE), 
	"APPROVED_TOTAL_UNITS" VARCHAR2(50 BYTE), 
	"CREATED_DATE" DATE DEFAULT sysdate, 
	"ENABLED" CHAR(1 BYTE) DEFAULT 'Y'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_ES_INTENT
--------------------------------------------------------

  CREATE TABLE "OPENACCESS"."T_ES_INTENT" 
   (	"ID" VARCHAR2(50 BYTE), 
	"SELLER_COMP_SERV_ID" VARCHAR2(50 BYTE), 
	"AGMT_PERIOD_CODE" VARCHAR2(50 BYTE), 
	"FROM_DT" DATE, 
	"TO_DT" DATE, 
	"IS_CAPTIVE" CHAR(1 BYTE), 
	"STATUS_CODE" VARCHAR2(50 BYTE), 
	"FROM_MONTH" VARCHAR2(100 BYTE), 
	"FROM_YEAR" VARCHAR2(100 BYTE), 
	"TO_MONTH" VARCHAR2(100 BYTE), 
	"TO_YEAR" VARCHAR2(100 BYTE), 
	"CREATED_DATE" DATE DEFAULT sysdate, 
	"ENABLED" CHAR(1 BYTE) DEFAULT 'Y', 
	"T_EWA_ID" VARCHAR2(50 BYTE), 
	"CODE" VARCHAR2(50 BYTE), 
	"FLOW_TYPE_CODE" VARCHAR2(50 BYTE), 
	"T_INPRINCIPLE_APPLN_ID" VARCHAR2(50 BYTE), 
	"T_NOC_GENERATOR_ID" VARCHAR2(50 BYTE), 
	"PROPOSED_CAPACITY" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_ES_INTENT_LINE
--------------------------------------------------------

  CREATE TABLE "OPENACCESS"."T_ES_INTENT_LINE" 
   (	"ID" VARCHAR2(50 BYTE), 
	"T_EST_INTENT_ID" VARCHAR2(50 BYTE), 
	"BUYER_COMP_SERV_ID" VARCHAR2(50 BYTE), 
	"STATUS_CODE" VARCHAR2(50 BYTE), 
	"T_NOC_ID" VARCHAR2(50 BYTE), 
	"T_CONSENT_ID" VARCHAR2(50 BYTE), 
	"T_OA_AGMT_ID" VARCHAR2(50 BYTE), 
	"PROPOSED_QUANTUM" VARCHAR2(100 BYTE), 
	"CREATED_DATE" DATE DEFAULT sysdate, 
	"ENABLED" CHAR(1 BYTE) DEFAULT 'Y', 
	"T_EPA_ID" VARCHAR2(50 BYTE), 
	"M_TRADE_RELATIONSHIP_ID" VARCHAR2(50 BYTE), 
	"IS_CAPTIVE" CHAR(1 BYTE), 
	"T_STANDING_CLEARENCE_ID" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_EWA
--------------------------------------------------------

  CREATE TABLE "OPENACCESS"."T_EWA" 
   (	"ID" VARCHAR2(50 BYTE), 
	"VERSION" VARCHAR2(50 BYTE), 
	"SELLER_COMP_SERV_ID" VARCHAR2(50 BYTE), 
	"SELLER_END_ORG_ID" VARCHAR2(100 BYTE), 
	"INJECTION_VOLTAGE_CODE" VARCHAR2(100 BYTE), 
	"TOTAL_PROPOSED_UNITS" VARCHAR2(50 BYTE), 
	"TOAL_APPROVED_UNITS" VARCHAR2(50 BYTE), 
	"AGMT_PERIOD_CODE" VARCHAR2(50 BYTE), 
	"FROM_DT" DATE, 
	"TO_DT" DATE, 
	"TOTAL_INJECTION_PEAK_UNITS" VARCHAR2(50 BYTE), 
	"TOTAL_INJECTION_OFF_PEAK_UNITS" VARCHAR2(50 BYTE), 
	"APPLIED_DT" DATE, 
	"APPROVED_DT" DATE, 
	"STATUS_CODE" VARCHAR2(50 BYTE), 
	"EWA_APPROVAL_NUMBER" VARCHAR2(50 BYTE), 
	"REMARKS" VARCHAR2(100 BYTE), 
	"CREATED_BY" VARCHAR2(50 BYTE), 
	"CREATED_DT" DATE, 
	"MODIFIED_BY" VARCHAR2(50 BYTE), 
	"MODIFIED_DT" DATE, 
	"T_ES_INTENT_ID" VARCHAR2(50 BYTE), 
	"TOTAL_DRAWAL_PEAK_UNITS" VARCHAR2(100 BYTE), 
	"TOTAL_DRAWAL_OFF_PEAK_UNITS" VARCHAR2(100 BYTE), 
	"SELLER_IS_CAPTIVE" CHAR(1 BYTE), 
	"AGREEMENT_DT" DATE, 
	"CREATED_DATE" DATE DEFAULT sysdate, 
	"ENABLED" CHAR(1 BYTE) DEFAULT 'Y', 
	"CODE" VARCHAR2(50 BYTE), 
	"FLOW_TYPE_CODE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_EWA_LINE
--------------------------------------------------------

  CREATE TABLE "OPENACCESS"."T_EWA_LINE" 
   (	"ID" VARCHAR2(50 BYTE), 
	"T_EWA_ID" VARCHAR2(50 BYTE), 
	"APPLIED_DT" DATE, 
	"APPROVED_DT" DATE, 
	"BUYER_COMP_SERV_ID" VARCHAR2(50 BYTE), 
	"BUYER_END_ORG_ID" VARCHAR2(100 BYTE), 
	"DRAWAL_VOLTAGE_CODE" VARCHAR2(50 BYTE), 
	"INJECTION_PEAK_UNITS" VARCHAR2(50 BYTE), 
	"INJECTION_OFF_PEAK_UNITS" VARCHAR2(50 BYTE), 
	"STATUS_CODE" VARCHAR2(50 BYTE), 
	"REMARKS" VARCHAR2(100 BYTE), 
	"CREATED_BY" VARCHAR2(50 BYTE), 
	"CREATED_DT" DATE, 
	"MODIFIED_BY" VARCHAR2(50 BYTE), 
	"MODIFIED_DT" DATE, 
	"DRAWAL_PEAK_UNITS" VARCHAR2(100 BYTE), 
	"DRAWAL_OFF_PEAK_UNITS" VARCHAR2(100 BYTE), 
	"EWA_LINE_CHANGE_CODE" VARCHAR2(100 BYTE), 
	"CREATED_DATE" DATE DEFAULT sysdate, 
	"ENABLED" CHAR(1 BYTE) DEFAULT 'Y', 
	"PROPOSED_UNITS" VARCHAR2(50 BYTE), 
	"APPROVED_UNITS" VARCHAR2(50 BYTE), 
	"IS_CAPTIVE" CHAR(1 BYTE), 
	"SHARE_PERCENTAGE" FLOAT(126), 
	"INTERVAL_TYPE_CODE" VARCHAR2(50 BYTE) DEFAULT '01'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_INPRINCIPLE_APPLN
--------------------------------------------------------

  CREATE TABLE "OPENACCESS"."T_INPRINCIPLE_APPLN" 
   (	"ID" VARCHAR2(50 BYTE), 
	"T_ES_INTENT_ID" VARCHAR2(50 BYTE), 
	"SELLER_COMP_SERV_ID" VARCHAR2(50 BYTE), 
	"AGMT_PERIOD_CODE" VARCHAR2(50 BYTE), 
	"FROM_DT" DATE, 
	"TO_DT" DATE, 
	"IS_CAPTIVE" CHAR(1 BYTE) DEFAULT 'N', 
	"STATUS_CODE" VARCHAR2(50 BYTE), 
	"FROM_MONTH" VARCHAR2(100 BYTE), 
	"FROM_YEAR" VARCHAR2(100 BYTE), 
	"TO_MONTH" VARCHAR2(100 BYTE), 
	"TO_YEAR" VARCHAR2(100 BYTE), 
	"CREATED_DATE" DATE DEFAULT sysdate, 
	"ENABLED" CHAR(1 BYTE) DEFAULT 'Y', 
	"CODE" VARCHAR2(50 BYTE), 
	"FLOW_TYPE_CODE" VARCHAR2(50 BYTE), 
	"PROPOSED_CAPACITY" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_INPRINCIPLE_APPLN_LINE
--------------------------------------------------------

  CREATE TABLE "OPENACCESS"."T_INPRINCIPLE_APPLN_LINE" 
   (	"ID" VARCHAR2(50 BYTE), 
	"T_INPRINCIPLE_APPLN_ID" VARCHAR2(50 BYTE), 
	"APPLIED_DT" DATE, 
	"APPROVED_DT" DATE, 
	"BUYER_COMP_SERV_ID" VARCHAR2(50 BYTE), 
	"BUYER_END_ORG_ID" VARCHAR2(100 BYTE), 
	"DRAWAL_VOLTAGE_CODE" VARCHAR2(50 BYTE), 
	"INJECTION_PEAK_UNITS" VARCHAR2(50 BYTE), 
	"INJECTION_OFF_PEAK_UNITS" VARCHAR2(50 BYTE), 
	"STATUS_CODE" VARCHAR2(50 BYTE), 
	"REMARKS" VARCHAR2(100 BYTE), 
	"CREATED_BY" VARCHAR2(50 BYTE), 
	"CREATED_DT" DATE, 
	"MODIFIED_BY" VARCHAR2(50 BYTE), 
	"MODIFIED_DT" DATE, 
	"DRAWAL_PEAK_UNITS" VARCHAR2(100 BYTE), 
	"DRAWAL_OFF_PEAK_UNITS" VARCHAR2(100 BYTE), 
	"CREATED_DATE" DATE DEFAULT sysdate, 
	"ENABLED" CHAR(1 BYTE) DEFAULT 'Y', 
	"PROPOSED_UNITS" VARCHAR2(50 BYTE), 
	"APPROVED_UNITS" VARCHAR2(50 BYTE), 
	"IS_CAPTIVE" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_NOC
--------------------------------------------------------

  CREATE TABLE "OPENACCESS"."T_NOC" 
   (	"ID" VARCHAR2(50 BYTE), 
	"TYPE_CODE" VARCHAR2(50 BYTE), 
	"STATUS_CODE" VARCHAR2(50 BYTE), 
	"BUYER_COMP_SERV_ID" VARCHAR2(50 BYTE), 
	"T_ES_INTENT_ID" VARCHAR2(50 BYTE), 
	"PROPOSED_CAPACITY" VARCHAR2(50 BYTE), 
	"EXEMPT_RC" CHAR(1 BYTE), 
	"HAS_DUES" CHAR(1 BYTE), 
	"DUE_DETAILS" VARCHAR2(500 BYTE), 
	"PENDING_CASE_DETAILS" VARCHAR2(500 BYTE), 
	"TECHNICAL_FEASIBILITY_DETAILS" VARCHAR2(500 BYTE), 
	"APPROVED_CAPACITY" VARCHAR2(100 BYTE), 
	"IS_CAPTIVE" CHAR(1 BYTE), 
	"AGMT_PERIOD_CODE" VARCHAR2(50 BYTE), 
	"AGREEMENT_DT" DATE, 
	"CREATED_DATE" DATE DEFAULT sysdate, 
	"ENABLED" CHAR(1 BYTE) DEFAULT 'Y', 
	"CODE" VARCHAR2(50 BYTE), 
	"FLOW_TYPE_CODE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_NOC_GENERATOR
--------------------------------------------------------

  CREATE TABLE "OPENACCESS"."T_NOC_GENERATOR" 
   (	"ID" VARCHAR2(50 BYTE), 
	"CODE" VARCHAR2(50 BYTE), 
	"T_ES_INTENT_ID" VARCHAR2(50 BYTE), 
	"T_INPRINCIPLE_APPLN_ID" VARCHAR2(50 BYTE), 
	"M_ORG_ID" VARCHAR2(50 BYTE), 
	"M_SUBSTATION_ID" VARCHAR2(50 BYTE), 
	"M_FEEDER_ID" VARCHAR2(50 BYTE), 
	"FUEL_TYPE_CODE" VARCHAR2(50 BYTE), 
	"CAPACITY" VARCHAR2(50 BYTE), 
	"AUXILIARY_CONSUMPTION" VARCHAR2(50 BYTE), 
	"IN_HOUSE_CONSUMPTION" VARCHAR2(50 BYTE), 
	"EX_BUS" VARCHAR2(50 BYTE), 
	"APPROVED_POWER_CAPACITY" VARCHAR2(50 BYTE), 
	"T_INPRIN_APPLN_QUANTUM" VARCHAR2(50 BYTE), 
	"T_INPRIN_APPLN_APPRV_DATE" VARCHAR2(50 BYTE), 
	"IS_ONLINE_DATA_MONITORING" CHAR(1 BYTE), 
	"IS_TANGEDCO" CHAR(1 BYTE), 
	"TANGEDCO_REF_NUMBER" VARCHAR2(50 BYTE), 
	"TANGEDCO_APPROVED_QUANTUM" VARCHAR2(50 BYTE), 
	"TANGEDCO_DATED" DATE, 
	"TANGEDCO_TILL_DATE" DATE, 
	"CAPTIVE_QUANTUM" VARCHAR2(50 BYTE), 
	"THIRD_PARTY_QUANTUM" VARCHAR2(50 BYTE), 
	"TRADER_QUANTUM" VARCHAR2(50 BYTE), 
	"OTHER_QUANTUM" VARCHAR2(50 BYTE), 
	"TOTAL_POWER_SALE_COMMITMENTS" VARCHAR2(50 BYTE), 
	"MAXIMUM_SURPLUS_QUANTUM" VARCHAR2(50 BYTE), 
	"CREATED_DATE" DATE DEFAULT sysdate, 
	"ENABLED" CHAR(1 BYTE) DEFAULT 'Y', 
	"FLOW_TYPE_CODE" VARCHAR2(50 BYTE), 
	"STATUS_CODE" VARCHAR2(50 BYTE), 
	"SELLER_COMP_SERV_ID" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_NOC_GENERATOR_LINE
--------------------------------------------------------

  CREATE TABLE "OPENACCESS"."T_NOC_GENERATOR_LINE" 
   (	"ID" VARCHAR2(50 BYTE), 
	"T_NOC_GENERATOR_ID" VARCHAR2(50 BYTE), 
	"APPLIED_DT" DATE, 
	"APPROVED_DT" DATE, 
	"BUYER_COMP_SERV_ID" VARCHAR2(50 BYTE), 
	"BUYER_END_ORG_ID" VARCHAR2(100 BYTE), 
	"DRAWAL_VOLTAGE_CODE" VARCHAR2(50 BYTE), 
	"INJECTION_PEAK_UNITS" VARCHAR2(50 BYTE), 
	"INJECTION_OFF_PEAK_UNITS" VARCHAR2(50 BYTE), 
	"STATUS_CODE" VARCHAR2(50 BYTE), 
	"REMARKS" VARCHAR2(100 BYTE), 
	"CREATED_BY" VARCHAR2(50 BYTE), 
	"CREATED_DT" DATE, 
	"MODIFIED_BY" VARCHAR2(50 BYTE), 
	"MODIFIED_DT" DATE, 
	"DRAWAL_PEAK_UNITS" VARCHAR2(100 BYTE), 
	"DRAWAL_OFF_PEAK_UNITS" VARCHAR2(100 BYTE), 
	"CREATED_DATE" DATE DEFAULT sysdate, 
	"ENABLED" CHAR(1 BYTE) DEFAULT 'Y', 
	"PROPOSED_UNITS" VARCHAR2(50 BYTE), 
	"APPROVED_UNITS" VARCHAR2(50 BYTE), 
	"IS_CAPTIVE" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_OAA
--------------------------------------------------------

  CREATE TABLE "OPENACCESS"."T_OAA" 
   (	"ID" VARCHAR2(50 BYTE), 
	"BUYER_COMP_SERV_ID" VARCHAR2(50 BYTE), 
	"BUYER_END_ORG_ID" VARCHAR2(100 BYTE), 
	"BUYER_END_UTILITY" VARCHAR2(100 BYTE), 
	"DRAWAL_TRANS_SS_ID" VARCHAR2(50 BYTE), 
	"DRAWAL_TRANS_VOLTAGE_CODE" VARCHAR2(50 BYTE), 
	"DRAWAL_TRANS_FEEDER_ID" VARCHAR2(50 BYTE), 
	"DRAWAL_DIST_SS_ID" VARCHAR2(50 BYTE), 
	"DRAWAL_DIST_VOLTAGE_CODE" VARCHAR2(50 BYTE), 
	"AGMT_PERIOD_CODE" VARCHAR2(50 BYTE), 
	"FROM_DT" DATE, 
	"TO_DT" DATE, 
	"PROPOSED_TOTAL_UNITS" VARCHAR2(50 BYTE), 
	"APPROVED_TOTAL_UNITS" VARCHAR2(50 BYTE), 
	"SELLER_COMP_SERV_ID" VARCHAR2(50 BYTE), 
	"SELLER_END_ORG_ID" VARCHAR2(100 BYTE), 
	"SELLER_END_UTILITY" VARCHAR2(100 BYTE), 
	"INJECTION_TRANS_SS_ID" VARCHAR2(50 BYTE), 
	"INJECTION_TRANS_VOLTAGE_CODE" VARCHAR2(50 BYTE), 
	"INJECTION_TRANS_FEEDER_ID" VARCHAR2(50 BYTE), 
	"INJECTION_DIST_SS_ID" VARCHAR2(50 BYTE), 
	"INJECTION_DIST_VOLTAGE_CODE" VARCHAR2(50 BYTE), 
	"PAYMENT_TYPE_CODE" VARCHAR2(50 BYTE), 
	"PAYMENT_BANK_DETAILS" VARCHAR2(200 BYTE), 
	"PAYMENT_TXN_NO" VARCHAR2(50 BYTE), 
	"PAYMENT_DATE" VARCHAR2(50 BYTE), 
	"PAYMENT_AMOUNT" VARCHAR2(50 BYTE), 
	"LICENSEE" VARCHAR2(50 BYTE), 
	"C1_UNITS" VARCHAR2(50 BYTE), 
	"C2_UNITS" VARCHAR2(50 BYTE), 
	"C3_UNITS" VARCHAR2(50 BYTE), 
	"C4_UNITS" VARCHAR2(50 BYTE), 
	"C5_UNITS" VARCHAR2(50 BYTE), 
	"APPLIED_DT" DATE, 
	"APPROVED_DT" DATE, 
	"STATUS_CODE" VARCHAR2(50 BYTE), 
	"CODE" VARCHAR2(50 BYTE), 
	"OAA_APPROVAL_NUMBER" VARCHAR2(50 BYTE), 
	"REMARKS" VARCHAR2(100 BYTE), 
	"CREATED_BY" VARCHAR2(50 BYTE), 
	"CREATED_DT" DATE, 
	"MODIFIED_BY" VARCHAR2(50 BYTE), 
	"MODIFIED_DT" DATE, 
	"T_ES_INTENT_ID" VARCHAR2(50 BYTE), 
	"AGREEMENT_DT" DATE, 
	"SELLER_IS_CAPTIVE" CHAR(1 BYTE), 
	"CREATED_DATE" DATE DEFAULT sysdate, 
	"ENABLED" CHAR(1 BYTE) DEFAULT 'Y', 
	"PEAK_UNITS" VARCHAR2(100 BYTE), 
	"OFF_PEAK_UNITS" VARCHAR2(100 BYTE), 
	"FLOW_TYPE_CODE" VARCHAR2(50 BYTE), 
	"INTERVAL_TYPE_CODE" VARCHAR2(50 BYTE), 
	"SHARE_PERCENT" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_PPA
--------------------------------------------------------

  CREATE TABLE "OPENACCESS"."T_PPA" 
   (	"ID" VARCHAR2(50 BYTE), 
	"CODE" VARCHAR2(50 BYTE), 
	"SELLER_COMP_SERV_ID" VARCHAR2(50 BYTE), 
	"AGREEMENT_DATE" DATE, 
	"PROPOSED_CAPACITY" VARCHAR2(50 BYTE), 
	"APPROVED_CAPACITY" VARCHAR2(50 BYTE), 
	"FROM_DATE" DATE, 
	"TO_DATE" DATE, 
	"C1" VARCHAR2(50 BYTE), 
	"C2" VARCHAR2(50 BYTE), 
	"C3" VARCHAR2(50 BYTE), 
	"C4" VARCHAR2(50 BYTE), 
	"C5" VARCHAR2(50 BYTE), 
	"PEAK_UNITS" VARCHAR2(50 BYTE), 
	"OFF_PEAK_UNITS" VARCHAR2(50 BYTE), 
	"CREATED_BY" VARCHAR2(50 BYTE), 
	"CREATED_DATE" DATE DEFAULT sysdate, 
	"ENABLED" CHAR(1 BYTE) DEFAULT 'Y', 
	"FROM_MONTH" VARCHAR2(50 BYTE), 
	"TO_YEAR" VARCHAR2(50 BYTE), 
	"FROM_YEAR" VARCHAR2(50 BYTE), 
	"TO_MONTH" VARCHAR2(50 BYTE), 
	"MODIFIED_DATE" DATE, 
	"MODIFIDED_BY" VARCHAR2(50 BYTE), 
	"BUYER_COMP_SERV_ID" VARCHAR2(50 BYTE), 
	"AGREEMENT_PERIOD_CODE" VARCHAR2(50 BYTE), 
	"FLOW_TYPE_CODE" VARCHAR2(50 BYTE), 
	"INTERVAL_TYPE_CODE" VARCHAR2(100 BYTE), 
	"SHARE_PERCENTAGE" FLOAT(126), 
	"IS_CAPTIVE" CHAR(1 BYTE), 
	"STATUS_CODE" VARCHAR2(50 BYTE), 
	"T_ES_INTENT_ID" VARCHAR2(50 BYTE), 
	"VOLTAGE_CODE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_STANDING_CLEARENCE
--------------------------------------------------------

  CREATE TABLE "OPENACCESS"."T_STANDING_CLEARENCE" 
   (	"ID" VARCHAR2(50 BYTE), 
	"SLDC_NAME" VARCHAR2(50 BYTE), 
	"REGION" VARCHAR2(50 BYTE), 
	"BUYER_COMP_SERV_ID" VARCHAR2(50 BYTE), 
	"T_ES_INTENT_ID" VARCHAR2(50 BYTE), 
	"MAX_DRAWAL_CEILING" VARCHAR2(50 BYTE), 
	"CREATED_BY" VARCHAR2(50 BYTE), 
	"CREATED_DATE" DATE DEFAULT sysdate, 
	"APPROVAL_DATE" DATE, 
	"ENABLED" CHAR(1 BYTE) DEFAULT 'Y', 
	"FROM_DATE" DATE, 
	"TO_DATE" DATE, 
	"FROM_MONTH" VARCHAR2(50 BYTE), 
	"TO_YEAR" VARCHAR2(50 BYTE), 
	"FROM_YEAR" VARCHAR2(50 BYTE), 
	"TO_MONTH" VARCHAR2(50 BYTE), 
	"STATE_TRANS_LOSS" VARCHAR2(50 BYTE), 
	"STATE_TRANS_LOSS_PERCENT" VARCHAR2(50 BYTE), 
	"STATE_TRANS_CHARGES" VARCHAR2(50 BYTE), 
	"STATE_TRANS_CHARGES_PERCENT" VARCHAR2(50 BYTE), 
	"SCHEDULING_CHARGES" VARCHAR2(50 BYTE), 
	"SCHEDULING_CHARGES_PERCENT" VARCHAR2(50 BYTE), 
	"SYSTEM_OPR_CHARGES" VARCHAR2(50 BYTE), 
	"SYSTEM_OPR_CHARGES_PERCENT" VARCHAR2(50 BYTE), 
	"MODIFIED_BY" VARCHAR2(50 BYTE), 
	"MODIFIED_DATE" DATE, 
	"M_ORG_ID" VARCHAR2(50 BYTE), 
	"CODE" VARCHAR2(50 BYTE), 
	"STATUS_CODE" VARCHAR2(50 BYTE), 
	"M_FEEDER_ID" VARCHAR2(50 BYTE), 
	"M_SUBSTATION_ID" VARCHAR2(50 BYTE), 
	"FLOW_TYPE_CODE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Function DELETE_ALL_MASTER_RECORDS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "OPENACCESS"."DELETE_ALL_MASTER_RECORDS" RETURN VARCHAR2 AS 
BEGIN

 DELETE FROM T_OAA;
 DELETE FROM F_AGREEMENT_LINE;
 DELETE FROM F_AGREEMENT;
 DELETE FROM T_EWA_LINE;
 DELETE FROM T_EWA;
 DELETE FROM T_STANDING_CLEARENCE;
 DELETE FROM T_EPA_LINES;
 DELETE FROM T_EPA ;
 DELETE FROM T_PPA;
 DELETE FROM T_CONSENT;
 DELETE FROM T_NOC_GENERATOR_LINE;
 DELETE FROM T_NOC_GENERATOR;
 DELETE FROM T_NOC;
 DELETE FROM T_INPRINCIPLE_APPLN_LINE;
 DELETE FROM T_INPRINCIPLE_APPLN;
 DELETE FROM T_ES_INTENT_LINE;
 DELETE FROM T_ES_INTENT;
 DELETE FROM T_CS_ID_TABLEA;
 DELETE FROM T_CS_ID_TABLEB;
 DELETE FROM T_CS_LOAN;
 DELETE FROM T_CS_QUANTUM_ALLOCATION;
 DELETE FROM T_CS;
 DELETE FROM M_TRADE_RELATIONSHIP;
 DELETE FROM M_GENERATOR ;
 DELETE FROM M_POWERPLANT ;
 DELETE FROM T_COMPANY_NAME_CHANGE;
 DELETE FROM T_COMPANY_METER_CHANGE;

 DELETE FROM M_COMPANY_SHAREHOLDER;
 DELETE FROM M_COMPANY_METER where id in (select M_COMPANY_METER_ID FROM V_COMPANY_SERVICE WHERE COMP_SER_TYPE_CODE = '03' AND NOT (m_company_code = 'IEX' OR m_company_code = 'TNEB'));
 DELETE FROM M_COMPANY_SERVICE where id in  (select id FROM V_COMPANY_SERVICE WHERE COMP_SER_TYPE_CODE = '03' AND NOT (m_company_code = 'IEX' OR m_company_code = 'TNEB'));
 DELETE FROM M_COMPANY where id in  (select M_COMPANY_ID FROM V_COMPANY_SERVICE WHERE COMP_SER_TYPE_CODE = '03' AND NOT (m_company_code = 'IEX' OR m_company_code = 'TNEB'));

 UPDATE M_SIGNUP SET IS_COMPLETE = 'N' WHERE PURPOSE = '02';

 COMMIT;

 return 'SUCCESS';
 END DELETE_ALL_MASTER_RECORDS;

/
