--------------------------------------------------------
--  File created - Monday-April-09-2018   
--------------------------------------------------------
DROP FUNCTION "OPENACCESS"."DELETE_ALL_GRID_CONNECTIVITY";
--------------------------------------------------------
--  DDL for Table T_GC_APPLICATION_STATUS
--------------------------------------------------------

  CREATE TABLE "OPENACCESS"."T_GC_APPLICATION_STATUS" 
   (	"ID" VARCHAR2(50 BYTE), 
	"GC_ID" VARCHAR2(50 BYTE), 
	"GC_STATUS_TYPE_CODE" VARCHAR2(50 BYTE), 
	"GC_STATUS_UPDATE_DATE" VARCHAR2(50 BYTE), 
	"GC_STATUS_UPDATE_BY" VARCHAR2(50 BYTE), 
	"GC_STATUS_REMARKS" VARCHAR2(300 BYTE), 
	"CREATED_BY" VARCHAR2(50 BYTE), 
	"CREATED_DATE" DATE DEFAULT sysdate, 
	"MODIFIED_BY" VARCHAR2(50 BYTE), 
	"MODIFIED_DATE" DATE, 
	"ENABLED" CHAR(1 BYTE) DEFAULT 'Y'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_GC_CHECKLIST
--------------------------------------------------------

  CREATE TABLE "OPENACCESS"."T_GC_CHECKLIST" 
   (	"ID" VARCHAR2(50 BYTE), 
	"GC_ID" VARCHAR2(50 BYTE), 
	"CHECKLIST_CODE" VARCHAR2(50 BYTE), 
	"IS_COMPLETE" CHAR(1 BYTE), 
	"COMPLETED_DT" DATE, 
	"REMARKS" VARCHAR2(300 BYTE), 
	"CREATED_BY" VARCHAR2(50 BYTE), 
	"CREATED_DATE" DATE DEFAULT sysdate, 
	"MODIFIED_BY" VARCHAR2(50 BYTE), 
	"MODIFIED_DATE" DATE, 
	"ENABLED" CHAR(1 BYTE) DEFAULT 'Y'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_GC_GEN_UNIT
--------------------------------------------------------

  CREATE TABLE "OPENACCESS"."T_GC_GEN_UNIT" 
   (	"ID" VARCHAR2(50 BYTE), 
	"GC_ID" VARCHAR2(50 BYTE), 
	"NAME" VARCHAR2(100 BYTE), 
	"CAPACITY" VARCHAR2(25 BYTE), 
	"MAKE_CODE" VARCHAR2(50 BYTE), 
	"MW_RATING" VARCHAR2(50 BYTE), 
	"MV_RATING" VARCHAR2(50 BYTE), 
	"KV_RATING" VARCHAR2(50 BYTE), 
	"DAMPING_FACTOR" VARCHAR2(50 BYTE), 
	"AMATEUR_RESISTANCE" VARCHAR2(50 BYTE), 
	"DIRECT_ASSISTANCE_REACTANCE" VARCHAR2(50 BYTE), 
	"NEGATIVE_SEQUENCE_REACTANCE" VARCHAR2(50 BYTE), 
	"ZERO_SEQUENCE_REACTANCE" VARCHAR2(50 BYTE), 
	"IS_CAPTIVE" CHAR(1 BYTE), 
	"WINDING_CONNECTION" VARCHAR2(50 BYTE), 
	"MASS_NUMBER" VARCHAR2(50 BYTE), 
	"STIFFNESS_COEFFICIENT" VARCHAR2(50 BYTE), 
	"SERIAL_NO" VARCHAR2(1000 BYTE), 
	"ROTOR_DIA" VARCHAR2(25 BYTE), 
	"HUB_HEIGHT" VARCHAR2(25 BYTE), 
	"REMARKS" VARCHAR2(300 BYTE), 
	"CREATED_BY" VARCHAR2(50 BYTE), 
	"CREATED_DATE" DATE DEFAULT sysdate, 
	"MODIFIED_BY" VARCHAR2(50 BYTE), 
	"MODIFIED_DATE" DATE, 
	"ENABLED" CHAR(1 BYTE) DEFAULT 'Y'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_GC_ID_TABLEA
--------------------------------------------------------

  CREATE TABLE "OPENACCESS"."T_GC_ID_TABLEA" 
   (	"ID" VARCHAR2(50 BYTE), 
	"GC_ID" VARCHAR2(50 BYTE), 
	"CLASS_OF_EQUTIY_SHARES" VARCHAR2(50 BYTE), 
	"NUMBER_OF_EQUTIY_SHARES" VARCHAR2(50 BYTE), 
	"VALUE_OF_EQUTIY_SHARES" VARCHAR2(50 BYTE), 
	"AMOUNT_OF_EQUTIY_SHARES" VARCHAR2(50 BYTE), 
	"NUMBER_OF_VOTING_RIGHTS" VARCHAR2(50 BYTE), 
	"PERCT_IN_EQUTIY_SHARES" VARCHAR2(50 BYTE), 
	"PERCT_IN_VOTING_RIGHTS" VARCHAR2(50 BYTE), 
	"PERCT_IN_VOTING_WITH_EQUITY" VARCHAR2(50 BYTE), 
	"REMARKS" VARCHAR2(300 BYTE), 
	"CREATED_BY" VARCHAR2(50 BYTE), 
	"CREATED_DATE" DATE DEFAULT sysdate, 
	"MODIFIED_BY" VARCHAR2(50 BYTE), 
	"MODIFIED_DATE" DATE, 
	"ENABLED" CHAR(1 BYTE) DEFAULT 'Y'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_GC_ID_TABLEB
--------------------------------------------------------

  CREATE TABLE "OPENACCESS"."T_GC_ID_TABLEB" 
   (	"ID" VARCHAR2(50 BYTE), 
	"GC_ID" VARCHAR2(50 BYTE), 
	"CLASS_OF_SHAREHOLDER" VARCHAR2(50 BYTE), 
	"NUMBER_OF_EQUTIY_SHARES" VARCHAR2(50 BYTE), 
	"VALUE_OF_EQUTIY_SHARES" VARCHAR2(50 BYTE), 
	"AMOUNT_OF_EQUTIY_SHARES" VARCHAR2(50 BYTE), 
	"NUMBER_OF_VOTING_RIGHTS" VARCHAR2(50 BYTE), 
	"PERCT_IN_EQUTIY_SHARES" VARCHAR2(50 BYTE), 
	"PERCT_IN_VOTING_RIGHTS" VARCHAR2(50 BYTE), 
	"PERCT_IN_VOTING_WITH_EQUITY" VARCHAR2(50 BYTE), 
	"REMARKS" VARCHAR2(300 BYTE), 
	"CREATED_BY" VARCHAR2(50 BYTE), 
	"CREATED_DATE" DATE DEFAULT sysdate, 
	"MODIFIED_BY" VARCHAR2(50 BYTE), 
	"MODIFIED_DATE" DATE, 
	"ENABLED" CHAR(1 BYTE) DEFAULT 'Y'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_GC_LOAN
--------------------------------------------------------

  CREATE TABLE "OPENACCESS"."T_GC_LOAN" 
   (	"ID" VARCHAR2(50 BYTE), 
	"GC_ID" VARCHAR2(50 BYTE), 
	"LOAN_ORIGIN" VARCHAR2(100 BYTE), 
	"SOURCE_NAME" VARCHAR2(50 BYTE), 
	"SOURCE_ADDRESS" VARCHAR2(50 BYTE), 
	"LOAN_AMOUNT" VARCHAR2(50 BYTE), 
	"CURRENCY" VARCHAR2(50 BYTE), 
	"EXCHANGE_RATE" VARCHAR2(50 BYTE), 
	"REMARKS" VARCHAR2(300 BYTE), 
	"CREATED_BY" VARCHAR2(50 BYTE), 
	"CREATED_DATE" DATE DEFAULT sysdate, 
	"MODIFIED_BY" VARCHAR2(50 BYTE), 
	"MODIFIED_DATE" DATE, 
	"ENABLED" CHAR(1 BYTE) DEFAULT 'Y'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_GC_QUANTUM_ALLOCATION
--------------------------------------------------------

  CREATE TABLE "OPENACCESS"."T_GC_QUANTUM_ALLOCATION" 
   (	"ID" VARCHAR2(50 BYTE), 
	"GC_ID" VARCHAR2(50 BYTE), 
	"BUYER_COMP_SERV_ID" VARCHAR2(50 BYTE), 
	"BUYER_ORG_ID" VARCHAR2(50 BYTE), 
	"CAPTIVE_COMPANY_NAME" VARCHAR2(50 BYTE), 
	"QUANTUM" VARCHAR2(50 BYTE), 
	"INJECTING_VOLTAGE_CODE" VARCHAR2(50 BYTE), 
	"DRAWAL_VOLTAGE_CODE" VARCHAR2(50 BYTE), 
	"REMARKS" VARCHAR2(300 BYTE), 
	"CREATED_BY" VARCHAR2(50 BYTE), 
	"CREATED_DATE" DATE DEFAULT sysdate, 
	"MODIFIED_BY" VARCHAR2(50 BYTE), 
	"MODIFIED_DATE" DATE, 
	"ENABLED" CHAR(1 BYTE) DEFAULT 'Y'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_GC_TRANSFORMERS
--------------------------------------------------------

  CREATE TABLE "OPENACCESS"."T_GC_TRANSFORMERS" 
   (	"ID" VARCHAR2(50 BYTE), 
	"GC_ID" VARCHAR2(50 BYTE), 
	"NAME" VARCHAR2(100 BYTE), 
	"MVA_RATING" VARCHAR2(50 BYTE), 
	"PRIMARY_VOLTAGE_CODE" VARCHAR2(50 BYTE), 
	"SECONDARY_VOLTAGE_CODE" VARCHAR2(50 BYTE), 
	"COOLING_TYPE" VARCHAR2(50 BYTE), 
	"WINDING_CONFIGURATION" VARCHAR2(50 BYTE), 
	"BREAKER_RATING" VARCHAR2(50 BYTE), 
	"TAP_SETTING" VARCHAR2(50 BYTE), 
	"TAP_NUMBER_MAX" VARCHAR2(50 BYTE), 
	"TAP_NUMBER_MIN" VARCHAR2(50 BYTE), 
	"TAP_RATIO" VARCHAR2(50 BYTE), 
	"TAP_STEP" VARCHAR2(50 BYTE), 
	"TAP_VOLTAGE_MAX" VARCHAR2(50 BYTE), 
	"TAP_VOLTAGE_MIN" VARCHAR2(50 BYTE), 
	"PHASE_DISPLACEMENT" VARCHAR2(50 BYTE), 
	"IMPEDENCE_PERCENTAGE" VARCHAR2(50 BYTE), 
	"LEAK_REACTANCE" VARCHAR2(50 BYTE), 
	"RESISTANCE" VARCHAR2(50 BYTE), 
	"REACTANCE" VARCHAR2(50 BYTE), 
	"REMARKS" VARCHAR2(300 BYTE), 
	"CREATED_BY" VARCHAR2(50 BYTE), 
	"CREATED_DATE" DATE DEFAULT sysdate, 
	"MODIFIED_BY" VARCHAR2(50 BYTE), 
	"MODIFIED_DATE" DATE, 
	"ENABLED" CHAR(1 BYTE) DEFAULT 'Y'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_GRID_CONNECTIVITY
--------------------------------------------------------

  CREATE TABLE "OPENACCESS"."T_GRID_CONNECTIVITY" 
   (	"ID" VARCHAR2(50 BYTE), 
	"APPLICATION_NUMBER" VARCHAR2(50 BYTE), 
	"GENERATING_TYPE_NAME" VARCHAR2(50 BYTE), 
	"PLANT_NAME" VARCHAR2(50 BYTE), 
	"COMPANY_NAME" VARCHAR2(50 BYTE), 
	"TEMP_HT_SUPPLY_NUMBER" VARCHAR2(50 BYTE), 
	"M_SUBSTATION_ID" VARCHAR2(50 BYTE), 
	"PROPOSED_COMMISSION_DT" DATE, 
	"VOLTAGE_CODE" VARCHAR2(50 BYTE), 
	"CLASS_VOLTAGE_PHASE" VARCHAR2(50 BYTE), 
	"CLASS_VOLTAGE_FREQUENCY" VARCHAR2(50 BYTE), 
	"AVAILED_HT_SUPPLY" VARCHAR2(50 BYTE), 
	"AVAILED_SANCTIONED_DEMAND" VARCHAR2(50 BYTE), 
	"FUEL_TYPE_CODE" VARCHAR2(50 BYTE), 
	"FUEL_LINKAGE_ARRANGED" VARCHAR2(50 BYTE), 
	"FUEL_LINKAGE_DETAILS" VARCHAR2(50 BYTE), 
	"STATUS_CODE" VARCHAR2(50 BYTE), 
	"LINE1" VARCHAR2(100 BYTE), 
	"CITY" VARCHAR2(50 BYTE), 
	"TOWN" VARCHAR2(50 BYTE), 
	"STATE_CODE" VARCHAR2(50 BYTE), 
	"PINCODE" VARCHAR2(50 BYTE), 
	"VILLAGE" VARCHAR2(50 BYTE), 
	"TALUK_CODE" VARCHAR2(50 BYTE), 
	"DISTRICT_CODE" VARCHAR2(50 BYTE), 
	"PLS_SF_NO" VARCHAR2(50 BYTE), 
	"PL_VILLAGE" VARCHAR2(50 BYTE), 
	"PL_TOWN" VARCHAR2(50 BYTE), 
	"PL_TALUK_CODE" VARCHAR2(50 BYTE), 
	"PL_DISTRICT_CODE" VARCHAR2(50 BYTE), 
	"WIND_PASS_CODE" VARCHAR2(50 BYTE), 
	"WIND_ZONE_AREA_CODE" VARCHAR2(50 BYTE), 
	"SCO_TAMILNADU" VARCHAR2(50 BYTE), 
	"SCO_MINISTRY" VARCHAR2(50 BYTE), 
	"SCO_CIVIL" VARCHAR2(50 BYTE), 
	"CG_INDUSTRY_TYPE" VARCHAR2(50 BYTE), 
	"CG_SUPPORT_FUEL" VARCHAR2(50 BYTE), 
	"CG_IS_PARALLEL_RUN" VARCHAR2(50 BYTE), 
	"CG_IS_STANDBY" VARCHAR2(50 BYTE), 
	"CG_CYCLE" VARCHAR2(50 BYTE), 
	"CG_HAS_PROOF" VARCHAR2(50 BYTE), 
	"PLANT_CAPACITY" VARCHAR2(50 BYTE), 
	"ANNUAL_EXPECTED_QUANTUM" VARCHAR2(50 BYTE), 
	"EXPECTED_CUF" VARCHAR2(50 BYTE), 
	"AUXILIARY_CONSUMPTION" VARCHAR2(50 BYTE), 
	"INDUSTRIAL_CONSUMPTION" VARCHAR2(50 BYTE), 
	"PER_UNIT_COST" VARCHAR2(50 BYTE), 
	"FIRM_POWER" VARCHAR2(50 BYTE), 
	"INFIRM_POWER" VARCHAR2(50 BYTE), 
	"PROPOSED_POWER_STB" VARCHAR2(50 BYTE), 
	"PROPOSED_POWER_CAPTIVE" VARCHAR2(50 BYTE), 
	"PROPOSED_POWER_3PTY" VARCHAR2(50 BYTE), 
	"ID_TOTAL_COST" VARCHAR2(50 BYTE), 
	"ID_TOTAL_CURRENCY" VARCHAR2(50 BYTE), 
	"ID_TOTAL_EXCHANGE_RATE" VARCHAR2(50 BYTE), 
	"ID_PROPOSED_DEBT_EQUITY_RATIO" VARCHAR2(50 BYTE), 
	"FINAL_SUBSTATION_ID" VARCHAR2(50 BYTE), 
	"FINAL_FEEDER_ID" VARCHAR2(50 BYTE), 
	"FINAL_SS_TYPE_NAME" VARCHAR2(50 BYTE), 
	"FINAL_FEEDER_TYPE_NAME" VARCHAR2(50 BYTE), 
	"GEN_SERVICE_NUMBER" VARCHAR2(50 BYTE), 
	"GEN_SERVICE_APPROVAL_NUMBER" VARCHAR2(50 BYTE), 
	"GEN_SERVICE_DATE" DATE, 
	"FINAL_COD" DATE, 
	"FINAL_COPD" DATE, 
	"FINAL_IS_STB" CHAR(1 BYTE), 
	"FINAL_IS_WHEELING" CHAR(1 BYTE), 
	"FINAL_PP_RATE" VARCHAR2(50 BYTE), 
	"FINAL_STB_TARIFF_ORDER" VARCHAR2(50 BYTE), 
	"FINAL_STB_TENDER_NUMBER" VARCHAR2(50 BYTE), 
	"FINAL_STB_TENDER_DATE" DATE, 
	"FINAL_WHEELING_FROM_DATE" DATE, 
	"FINAL_WHEELING_TO_DATE" DATE, 
	"REMARKS" VARCHAR2(300 BYTE), 
	"CREATED_BY" VARCHAR2(50 BYTE), 
	"CREATED_DATE" DATE DEFAULT sysdate, 
	"MODIFIED_BY" VARCHAR2(50 BYTE), 
	"MODIFIED_DATE" DATE, 
	"ENABLED" CHAR(1 BYTE) DEFAULT 'Y', 
	"M_ORG_ID" VARCHAR2(100 BYTE), 
	"GENERATING_TYPE_ISCAPTIVE" VARCHAR2(50 BYTE), 
	"METER_CT1" VARCHAR2(50 BYTE), 
	"METER_CT2" VARCHAR2(50 BYTE), 
	"METER_CT3" VARCHAR2(50 BYTE), 
	"METER_PT1" VARCHAR2(50 BYTE), 
	"METER_PT2" VARCHAR2(50 BYTE), 
	"METER_PT3" VARCHAR2(50 BYTE), 
	"METER_NUMBER" VARCHAR2(50 BYTE), 
	"METER_MAKE_CODE" VARCHAR2(50 BYTE), 
	"ACCURACY_CLASS_CODE" VARCHAR2(50 BYTE), 
	"IS_ABTMETER" CHAR(1 BYTE), 
	"MF" VARCHAR2(50 BYTE), 
	"MODEM_NUMBER" VARCHAR2(50 BYTE), 
	"PL_PINCODE" VARCHAR2(50 BYTE), 
	"AVAILED_HT_SUPPLY_NO" VARCHAR2(50 BYTE), 
	"FINAL_ORG_ID" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_GRID_CONN_APPLN
--------------------------------------------------------

  CREATE TABLE "OPENACCESS"."T_GRID_CONN_APPLN" 
   (	"ID" VARCHAR2(50 BYTE), 
	"APPLN_NO" VARCHAR2(50 BYTE), 
	"APPLIED_DATE" DATE, 
	"APPROVAL_DATE" DATE, 
	"ACTIVATED_DATE" DATE, 
	"STATUS" VARCHAR2(50 BYTE), 
	"REMARKS" VARCHAR2(300 BYTE), 
	"CREATED_BY" VARCHAR2(50 BYTE), 
	"CREATED_DATE" DATE DEFAULT sysdate, 
	"MODIFIED_BY" VARCHAR2(50 BYTE), 
	"MODIFIED_DATE" DATE, 
	"ENABLED" CHAR(1 BYTE) DEFAULT 'Y'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Function DELETE_ALL_GRID_CONNECTIVITY
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "OPENACCESS"."DELETE_ALL_GRID_CONNECTIVITY" RETURN VARCHAR2 AS 
BEGIN


  DELETE FROM  T_GC_TRANSFORMERS;
  DELETE FROM  T_GC_APPLICATION_STATUS;
  DELETE FROM  T_GC_LOAN ;
  DELETE FROM  T_GC_ID_TABLEA;
  DELETE FROM  T_GC_ID_TABLEB;
  DELETE FROM  T_GC_QUANTUM_ALLOCATION;
  DELETE FROM  T_GC_CHECKLIST;
  DELETE FROM  T_GC_GEN_UNIT;
  DELETE FROM  T_GRID_CONN_APPLN ;
  DELETE FROM  T_GRID_CONNECTIVITY ;



 COMMIT;

 return 'SUCCESS';
 END DELETE_ALL_GRID_CONNECTIVITY ;

/
