export class servicehistory{
addedBuyerMComapnyId?:string; 
addedBuyerName?:string;
addedBuyerServiceNo?:string; 
commercialMonth?:string; 
commercialYear?:string; 
flowTypeCode?:string; 
fuelTypeCode?:string; 
id?:string; 
mCompServNumber?:string; 
mCompanyId?:string;
mCompanyName?:string; 
mOrgName?:string; 
migratedFrom?:string; 
migratedTo?:string; 
migrationMonth?:string; 
migrationYear?:string; 
nameChangeMonth?:string; 
nameChangeYear?:string; 
newName?:string; 
oldName?:string; 
removedBuyerMCompanyId?:string; 
removedBuyerName?:string; 
removedBuyerServiceno?:string; 
mc_month?:string;
mcyear?:string;
newmeterno?:string;
oldmeterno?:string;

}