export class SldcNOC {
    id: string;
    nocPurpose: string;
    nocCode: string;
    status: string;
    appliedNo: string;
    appliedDt: Date;
    periodStartDate: Date;
    periodEndDate: Date;
    compServNo: string;
    compName: string;
    plantAdr: string;
    commsAdr: string;
    installCapPlant: string;
    intlAuxilary: string;
    intlInhouseConsump: string;
    exBusAval: string;
    approvPwrEvacCap: string;
    fuelType: string;
    feederWithVoltLevel: string;
    substationWithVoltLevel: string;
    gridApprovalDt: Date;
    codDt: string;
    isAbtAndAmr: string;
    isMeterDownloadAndInstall: string;
    abyMeterName: string;
    meterMfName: string;
    ctRatioAndClassAcc: string;
    ptRatioAndClassAcc: string;
    tnebTangedcoThrowPpa: string;
    isDataMonitoringWithSldc: string;
    isCommitToTangedco: string;
    ccArrearsAval: string;
    isComplyWithOaRequirment: string;
    techRemark: string;
    legalRemark: string;
    commRemark: string;
    isExisting: string;
    tarrif: string;
    cntrctDemand: string;
    region: string;
    edc: string;
    section: string;
    extgTotalCommit: string;
    connFeederAndVoltLevel: string;
    connSubstationAndVoltLevel: string;
    existingKv: string;
    existingFeederType: string;
    newTotalCommit: string;
    eligibleQuantumInWv: string;
    isHtConPermitForOa: string;
    enabled: string;
    createdBy: string;
    createdDt: Date;
    modifiedBy: string;
    modifiedDt: Date;    
    dirRemark:string=null;
    dirReason:string;
    ceRemark:string=null;
    ceReason:string;
    nocOrigin:string;
    applRefNo:string;
    applnType:string;
    compServId:string;
    category1:string;
    category2:string;
    quantity:string;
    approvedQuantity:string;
    approvedPeriodStartDate:Date;
    approvedPeriodEndDate:Date;
    edcApprovalDate:Date;
    sldcNocLine: any;
    customerName:String;
    isSelected:boolean=false;
}
export class SldcNOCLine {
    id: string;
    tSldcNocId: string;
    compServNo: string;
    compName: string;
    commitType: string;
    aggrementType: string;
    fromPeriod: string;
    toPeriod: string;
    quantum: string;
    flowType: string;
    fuelGroup: string;
    noOfBuyer: string;
    customerName:String;
}

export class SldcApproval {
    id: string;
    appId: string;
    applRefNo: string;
    applNo: string;
    applDate: string;
    appCategory: string;
    customerName: string;
    entityInj: string;
    entityInjEdc: string;
    entityDrl: string;
    entityDrlEdc: string;
    periodStartDate: string;
    periodEndDate: string;
    quantum: string;
    category1: string;
    category2: string;
    eorRegType: string;
    eosGcApprovalNumber: string;
    eosFeederNameSeller: string;
    eosVolLvlFeeder: string;
    eosInjSubstation: string;
    eosVolLvlSubstation: string;
    eocLossPer: string;
    evacuationCapacity: string;
    eosUtilInjEmbed: string;
    eosUtilInjEmbedLabel: string;
    eobUtilDrawalEmbedLabel: string;
    eobUtilDraEmbed: string;
    eobHtConsumerNumber: string;
    eobFeederNameBuyer: string;
    eobVolLvlFeeder: string;
    eobDrawalSubstation: string;
    eobDrawalLimit: string;
    eobBuyerType: string;
    eoiRegName: string;
    eoiRegAddress: string;
    eoiRegMobile1No: string;
    edcStatus: string;
    applicationStatus: string;
    appType: string;
    batchKey: string;
    isClean: string;
    inputRemarks: string;
    enabled: string;
    createdBy: string;
    createdDt: string;
    modifiedBy: string;
    modifiedDt: string;
    ipApprNo: string;
    sellerEdcCode: String;
    buyerEdcCode: String;
    approvalNo: String;
}

export class VCompanyService{
    companyName: String;
    mCompServNumber: String;
    capacity:String;
}