
UPDATE "OPENACCESS"."M_CHARGES_MAP" SET FF = 'N' WHERE id='1';
UPDATE "OPENACCESS"."M_CHARGES_MAP" SET FF = '04' WHERE id='2';
UPDATE "OPENACCESS"."M_CHARGES_MAP" SET FF = 'Y' WHERE id='3';
UPDATE "OPENACCESS"."M_CHARGES_MAP" SET FF = 'Y' WHERE id='4';
UPDATE "OPENACCESS"."M_CHARGES_MAP" SET FF = 'N' WHERE id='5';
UPDATE "OPENACCESS"."M_CHARGES_MAP" SET FF = 'N' WHERE id='6';
UPDATE "OPENACCESS"."M_CHARGES_MAP" SET FF = 'Y' WHERE id='7';
UPDATE "OPENACCESS"."M_CHARGES_MAP" SET FF = 'Y' WHERE id='8';
UPDATE "OPENACCESS"."M_CHARGES_MAP" SET FF = 'Y' WHERE id='9';
commit;