
ALTER TABLE IMPORT_TRADE_REL ADD FLOW_TYPE_CODE VARCHAR2(100) ;
ALTER TABLE IMPORT_TRADE_REL ADD result VARCHAR2(100) ;
ALTER TABLE IMPORT_TRADE_REL ADD result_desc VARCHAR2(1000) ;
ALTER TABLE IMPORT_TRADE_REL  MODIFY (IMPORT_REMARKS VARCHAR2(1000 BYTE) );
ALTER TABLE IMPORT_SELLERS ADD FLOW_TYPE_CODE VARCHAR2(100) ;
ALTER TABLE m_signup ADD FLOW_TYPE_CODE VARCHAR2(100) ;
ALTER TABLE M_SIGNUP_TRADE_REL ADD FLOW_TYPE_CODE VARCHAR2(100) ;
ALTER TABLE IMPORT_SELLERS  MODIFY (IMPORT_REMARKS VARCHAR2(1000 BYTE) );

DROP SEQUENCE  "T_ES_CHARGE_SEQ" ;
CREATE SEQUENCE  "T_ES_CHARGE_SEQ"  MINVALUE 1 MAXVALUE 99999999999 INCREMENT BY 1 START WITH 10000000 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


--THERMAL changes for charges
ALTER TABLE M_CHARGES_MAP ADD (FF VARCHAR2(20) );
CREATE OR REPLACE FORCE EDITIONABLE VIEW V_CHARGE as
    SELECT charge_code, charge_type_code,charge_desc, unit_charge, formula,d.remarks charge_defn_remarks, context,ff FROM  M_CHARGE_DEFN d, M_CHARGES_MAP m WHERE d.id = m.m_charge_id;


ALTER TABLE T_ACTIVITY_LOG 
ADD (ATT4 VARCHAR2(500) );

ALTER TABLE T_ACTIVITY_LOG  
MODIFY (ACTIVITY_NAME VARCHAR2(500 BYTE) );

ALTER TABLE T_ACTIVITY_LOG  
MODIFY (CREATED_BY VARCHAR2(500 BYTE) );

ALTER TABLE T_ACTIVITY_LOG  
MODIFY (ATT1 VARCHAR2(500 BYTE) );

ALTER TABLE T_ACTIVITY_LOG  
MODIFY (ATT2 VARCHAR2(500 BYTE) );

ALTER TABLE T_ACTIVITY_LOG  
MODIFY (ATT3 VARCHAR2(500 BYTE) );

  CREATE TABLE "DOC_INFO" 
   (	"ID" VARCHAR2(50) NOT NULL ENABLE, 
	"DOC_NAME" VARCHAR2(255) DEFAULT NULL, 
	"FILTER_CRITERIA" VARCHAR2(255) DEFAULT NULL, 
	"DOC_PATH" VARCHAR2(255) DEFAULT NULL, 
	"FILE_NAME" VARCHAR2(255) DEFAULT NULL, 
	"FILE_NAME_TO_USER" VARCHAR2(255) DEFAULT NULL, 
	"FILE_EXTENSION" VARCHAR2(255) DEFAULT NULL, 
	"TABLE_ID" VARCHAR2(255) DEFAULT NULL, 
	"BATCH_KEY" VARCHAR2(255) DEFAULT NULL, 
	"IS_ENABLED" VARCHAR2(255) DEFAULT NULL, 
	"CREATED_BY" VARCHAR2(255) DEFAULT NULL, 
	"CREATED_DT" TIMESTAMP (6) DEFAULT NULL, 
	 CONSTRAINT "DOC_INFO_PK" PRIMARY KEY ("ID")
   );

ALTER TABLE TEMP_V_COMP_REFRESH 
ADD (EXCESS_UNIT_TYPE VARCHAR2(50) );

ALTER TABLE TEMP_V_COMP_REFRESH 
ADD (EXCESS_UNIT_TYPE_REASON VARCHAR2(100) );


CREATE OR REPLACE VIEW V_COMPANY_SERVICE
AS select temp.ID,temp.BANKING_SERVICE_ID,temp.BANKING_SERVICE_NUMBER,temp.CAPACITY,temp.COMMISSION_DATE,temp.COMPANY_IS_INTERNAL,temp.COMP_SER_TYPE_CODE,temp.COMP_SER_TYPE_NAME,
temp.DL_SERVICE_ID,temp.DL_SERVICE_NUMBER,temp.ENABLED,temp.FLOW_TYPE_CODE,temp.FUEL_TYPE_CODE,temp.FUEL_TYPE_NAME,temp.FUEL_GROUP_NAME,temp.ACCURACY_CLASS_CODE,temp.IS_ABTMETER,temp.IS_BUYER,
temp.IS_REC,temp.IS_SELLER,temp.METER_CT1,temp.METER_CT2,temp.METER_CT3,temp.METER_MAKE_CODE,temp.METER_NUMBER,temp.METER_PT1,temp.METER_PT2,temp.METER_PT3,
temp.MF,temp.MODEM_NUMBER,temp.M_COMPANY_CODE,temp.M_COMPANY_ID,temp.M_COMPANY_METER_ID,temp.M_COMPANY_NAME,temp.M_COMP_SERV_NUMBER,temp.M_FEEDER_CODE,temp.M_FEEDER_ID,
temp.M_FEEDER_NAME,temp.M_ORG_CODE,temp.M_ORG_ID,temp.M_ORG_NAME,temp.M_SECTION_CODE,temp.M_SECTION_ID,temp.M_SECTION_NAME,temp.M_SUBSTATION_CODE,temp.M_SUBSTATION_ID,
temp.M_SUBSTATION_NAME,temp.REF_NUMBER,temp.TARIFF,temp.TL_SERVICE_ID,temp.TL_SERVICE_NUMBER,temp.TYPE_OF_SS,temp.UNADJUSTED_SERVICE_ID,temp.UNADJUSTED_SERVICE_NUMBER,
temp.VOLTAGE_CODE,temp.VOLTAGE_NAME,temp."number",temp.IS_CAPTIVE,temp.IS_STB,temp.IS_THIRD_PARTY,temp.TR_FLOW_TYPE_CODE, temp.EXCESS_UNIT_TYPE, temp.EXCESS_UNIT_TYPE_REASON
from temp_v_comp_refresh temp;


ALTER TABLE int_adjusted_unit 
ADD (result_desc VARCHAR2(1000) );
