ALTER TABLE T_SLDC_NOC MODIFY COMP_NAME VARCHAR2(200);
ALTER TABLE T_SLDC_NOC MODIFY COMP_SERV_NO VARCHAR2(100);
ALTER TABLE T_SLDC_NOC MODIFY INSTALL_CAP_PLANT VARCHAR2(500);
ALTER TABLE T_SLDC_NOC MODIFY INTL_AUXILARY VARCHAR2(500);
ALTER TABLE T_SLDC_NOC MODIFY FEEDER_WITH_VOLT_LEVEL VARCHAR2(500);
ALTER TABLE T_SLDC_NOC MODIFY SUBSTATION_WITH_VOLT_LEVEL VARCHAR2(500);
ALTER TABLE T_SLDC_NOC MODIFY TECH_REMARK VARCHAR2(500);
ALTER TABLE T_SLDC_NOC MODIFY LEGAL_REMARK VARCHAR2(500);
ALTER TABLE T_SLDC_NOC MODIFY COMM_REMARK VARCHAR2(500);
ALTER TABLE T_SLDC_NOC MODIFY EDC VARCHAR2(500);
ALTER TABLE T_SLDC_NOC MODIFY REGION VARCHAR2(500);
ALTER TABLE EXT_SAMAST_APPLN add seller_ce_approval_date date;
ALTER TABLE EXT_SAMAST_APPLN add buyer_ce_approval_date date;
CREATE or replace VIEW v_ext_samast_appln AS  
select id, appl_no, appl_ref_no, appl_date, SELLER_SLDC_NOC_ID, SELLER_NOC_START_DT, SELLER_NOC_END_DT,SELLER_NOC_QUANTITY, SELLER_NOC_STATUS, 
BUYER_SLDC_NOC_ID, BUYER_NOC_START_DT, BUYER_NOC_END_DT, BUYER_NOC_QUANTITY, BUYER_NOC_STATUS, seller_ce_approval_date, buyer_ce_approval_date
from ext_samast_appln;