CREATE TABLE "T_BLOCK_TXN" 
   (	
    "ID" VARCHAR2(50 BYTE)  NOT NULL, 
	"M_ORG_ID" VARCHAR2(50 BYTE)  NOT NULL, 
	"M_COMP_SERVICE_ID" VARCHAR2(50 BYTE) NOT NULL,
	"M_COMP_SERVICE_NUMBER" VARCHAR2(20 BYTE) NOT NULL, 
	"YEAR" VARCHAR2(20 BYTE) NOT NULL,
	"MONTH" VARCHAR2(20 BYTE) NOT NULL,
	"TRANSACTION_TYPE" VARCHAR2(100 BYTE),
	"STATUS" VARCHAR2(100 BYTE), 
	"CREATED_DT" DATE NOT NULL, 
	"CREATED_BY" VARCHAR2(50 BYTE) DEFAULT SYSDATE NOT NULL,
	"MODIFIED_BY" VARCHAR2(50 BYTE) DEFAULT SYSDATE NOT NULL,
	"MODIFIED_DATE" DATE NOT NULL, 
    CONSTRAINT "T_BLOCK_TXN_PK" PRIMARY KEY ("ID")
   );
  
  CREATE SEQUENCE  "T_BLOCK_TXN_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 ;
   
 
 
 ALTER TABLE T_BLOCK_TXN ADD REMARKS CLOB;
 
 