export class EnergyAdjustedOrder{
        id?:string;
        buyerServiceNumber?:string;
        sellerServiceNumber?:string;
        dSellCompName?:string;
        dSellOrgName?:string;
        dBuyerCompName?:string;
        dBuyerOrgName?:string;
        energySaleOrderId?:string;
        energySaleOrderLineId?:string;
        buyerCompServId?:string;
        sellerCompServId?:string;
        cleanStatus?:string;
        readingMonth?:string;
        readingYear?:string;
        readingDate?:string;
        adjustedC1?:string;
        adjustedC2?:string;
        adjustedC3?:string;
        adjustedC4?:string;
        adjustedC5?:string;
        htBankingC1?:string;
        htBankingC2?:string;
        htBankingC3?:string;
        htBankingC4?:string;
        htBankingC5?:string;
        htBankingWithLossC1?:string;
        htBankingWithLossC2?:string;
        htBankingWithLossC3?:string;
        htBankingWithLossC4?:string;
        htBankingWithLossC5?:string;
        allotedC1?:string;
        allotedC2?:string;
        allotedC3?:string;
        allotedC4?:string;
        allotedC5?:string;
        allotedNetC1?:string;
        allotedNetC2?:string;
        allotedNetC3?:string;
        allotedNetC4?:string;
        allotedNetC5?:string;
        lossPercent?:string;
        fuelTypeCode?:string;
        fuelName?:string;
    }

    export class MonthAndYear {
        month?:string;
        year?:string;
    }