// Generated by https://quicktype.io

export class OrgWiseGen {
  $$index:                 any;
    id:                    any;
    orgId:                 any;
    orgCode:               any;
    orgName:               any;
    companyId:             any;
    companyName:           any;
    sellerServiceId:       any;
    sellerServiceNumber:   any;
    voltageCode:           any;
    voltageName:           any;
    fuelCode:              any;
    fuelName:              any;
    genReportDate:         any;
    netGeneration:         any;
    month:                 any;
    year:                  any;
    totalUnits:            number;
    flowTypeCode:          any;
    isRec:                 any;
    totalImportGeneration: any;
    totalExportGeneration: any;
    plantClassTypeCode:    any;
    plantClassTypeDesc:    any;
    totalImportUnits:      any;
    totalExportUnits:      any;
    sumTotalImportUnits:   any;
    sumTotalExportUnits:   any;
    sumTotalUnits:         any;
    machineCapacity:       any;
    totalMachineCapacity:  any;
    sumMachineCapacity:    any;
    recCount: any;
    sumserviceCount: any;
  dispFuelTypeGroup: any;
  // index: any;
}
