export class Ewa {
	id: string;
	version: string;
	ewaNumber: string;
	ewaApprovalNumber: string;
	sellerOrgId: string;
	sellerOrgName: string;
	sellerCompServiceId: string;
	sellerCompServiceNumber: string;
	sellerCompanyName: string;
	sellerCompanyId: string;
	sellerCapacity: string;
	sellerPowerPlantFuelCode: string;
	sellerPowerPlantFuelDesc: string;
	sellerInjectionVoltageCode: string;
	sellerInjectionVoltageDesc: string;
	sellerIsCaptive: string;
	agreementPeriodCode: string;
	agreementPeriodDesc: string;
	fromDate: string;
	toDate: string;
	periodDuration: string;
	totalProposedUnits: string;
	totalApprovedUnits: string;
	totalInjectionPeakUnits: string;
	totalInjectionOffPeakUnits: string;
	totalDrawalPeakUnits: string;
	totalDrawalOffPeakUnits: string;
	appliedDate: string;
	approvedDate: string;
	statusCode: string;
	statusDesc: string;
	remarks: string;
	createdBy: string;
	createdDate: string;
	modifiedBy: string;
	modifiedDate: string;
	t_es_intent_id: string;
	ewaLines: any;
	agreementDate?:string;
	flowTypeCode?:string;
}

export class EwaLines{
	id: string;
	ewaId: string;
	ewaApprovalNumber: string;
	buyerOrgId: string;
	buyerOrgName: string;
	buyerCompServiceId: string;
	buyerCompServiceNumber: string;
	buyerCompanyName: string;
	buyerCompanyId: string;
	buyerCapacity: string;
	drawalVoltageCode: string;
	drawalVoltageDesc: string;
	injectionPeakUnits: string;
	injectionOffPeakUnits: string;
	loss: string;
	drawalPeakUnits: string;
	drawalOffPeakUnits: string;
	appliedDate: string;
	approvedDate: string;
	statusCode: string;
	statusDesc: string;
	ewaLineChangeCode: string;
	ewaLineChangeDesc: string;
	remarks: string;
	createdBy: string;
	createdDate: string;
	modifiedBy: string;
	modifiedDate: string;
	proposedUnits:string;
	approvedUnits:string;
	isCaptive:string;
}