CREATE OR REPLACE PROCEDURE OPENACCESS.ADD_BUYERS AS 
BEGIN
 INSERT INTO M_SIGNUP(ID, COMPANY_NAME, PURPOSE, VOLTAGE, HTSC_NUMBER, SANCTIONED_QUANTUM, TOTAL_CAPACITY, M_ORG_ID,IS_COMPLETE,
 COMPANY_ADDRESS,  CREATED_BY, REMARKS) SELECT m_signup_seq.nextval, CONSUMERNAME, '01', C.VALUE_CODE, HT_REF_NO, DEMANDSANC, LOAD,
 CIRCLECODE,'N', ADDRESS1||' '||ADDRESS2||' '||ADDRESS3||' '||ADDRESS4||' '||CITY||'-'||PINCODE, 'admin','newserv03082019'
 FROM IMPORT_BUYERS LEFT JOIN V_CODES C ON list_code = 'VOLTAGE_CODE' AND  AVAILEDVOLT = C.ATTRIB1  ;

DECLARE v_result varchar2(150);
BEGIN
v_result := IMPORT_FROM_SIGNUP('newserv03082019');
dbms_output.put_line('v_result - '||v_result);
END;

END ADD_BUYERS;